/*
 * File: formCitas.ui.js
 * Date: Fri Jul 12 2019 11:54:51 GMT-0600 (Mountain Daylight Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formCitasUi = Ext.extend(Ext.Panel, {
    title: 'Citas',
    autoScroll: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    itemId: 'btnGuardar',
                    icon: 'images/iconos/calendar_add.png',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    itemId: 'btnEliminar',
                    icon: 'images/iconos/calendar_delete.png',
                    disabled: true,
                    ref: '../btnEliminar'
                }
            ]
        };
        this.items = [
            {
                xtype: 'form',
                padding: 10,
                border: false,
                itemId: 'frmMain',
                ref: 'frmMain',
                items: [
                    {
                        xtype: 'datefield',
                        fieldLabel: 'Fecha',
                        width: 100,
                        itemId: 'txtFecha',
                        name: 'fecha',
                        submitValue: false,
                        labelStyle: 'font-weight:bold',
                        ref: '../txtFecha'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Cliente',
                        width: 400,
                        itemId: 'cmbCliente',
                        name: 'id_cliente',
                        valueField: 'id_cliente',
                        displayField: 'nombre_fiscal',
                        allowBlank: false,
                        forceSelection: true,
                        enableKeyEvents: true,
                        minChars: 0,
                        pageSize: 20,
                        validateOnBlur: false,
                        labelStyle: 'font-weight:bold',
                        triggerConfig: {
                            tag: 'span',
                            cls: 'x-form-twin-triggers',
                            style: 'padding-right:2px',
                            cn: [
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-clear-trigger"
                                },
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-search-trigger"
                                }
                            ]
                        },
                        ref: '../cmbCliente'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Vendedor',
                        width: 400,
                        itemId: 'cmbAgente',
                        name: 'id_agente',
                        valueField: 'id_agente',
                        displayField: 'nombre_agente',
                        allowBlank: false,
                        forceSelection: true,
                        enableKeyEvents: true,
                        minChars: 0,
                        pageSize: 20,
                        validateOnBlur: false,
                        labelStyle: 'font-weight:bold',
                        triggerConfig: {
                            tag: 'span',
                            cls: 'x-form-twin-triggers',
                            style: 'padding-right:2px',
                            cn: [
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-clear-trigger"
                                },
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-search-trigger"
                                }
                            ]
                        },
                        ref: '../cmbAgente'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Horario',
                        width: 200,
                        itemId: 'cmbHorario',
                        name: 'id_horario',
                        valueField: 'id_horario',
                        displayField: 'descripcion_horario',
                        editable: false,
                        allowBlank: false,
                        forceSelection: true,
                        enableKeyEvents: true,
                        minChars: 0,
                        pageSize: 20,
                        validateOnBlur: false,
                        labelStyle: 'font-weight:bold',
                        triggerConfig: {
                            tag: 'span',
                            cls: 'x-form-twin-triggers',
                            style: 'padding-right:2px',
                            cn: [
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-clear-trigger"
                                },
                                {
                                    tag: "img",
                                    src: Ext.BLANK_IMAGE_URL,
                                    cls: "x-form-trigger x-form-search-trigger"
                                }
                            ]
                        },
                        ref: '../cmbHorario'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Observaciones',
                        width: 300,
                        itemId: 'txtObservaciones',
                        name: 'observaciones',
                        ref: '../txtObservaciones'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: '',
                        bubbleEvents: [
                            'cambioDeId'
                        ],
                        hidden: true,
                        hideLabel: true,
                        submitValue: false,
                        itemId: 'id_cita',
                        ref: '../txtIdCita'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'status',
                        value: 'A',
                        hidden: true,
                        hideLabel: true,
                        submitValue: false,
                        ref: '../txtStatus'
                    }
                ]
            }
        ];
        formCitasUi.superclass.initComponent.call(this);
    }
});
