/*
 * File: Main.js
 * Date: Fri Mar 04 2016 20:00:37 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
Ext.ns('miErpWeb.parametros');
var App = new Ext.App({});
Ext.override(Ext.grid.GridPanel, ekoGrid);

mew.permisos=new Array();
mew.Main = Ext.extend(MainUi, {
    initComponent: function() {
        mew.Main.superclass.initComponent.call(this);
		this.obtenerInformacionInicial();
		
		this.pnlMenu.on('click', function (n, e) {
            // this.cargarTab(node); //comentao
			if (n.leaf) {
				var params={
					xtype:n.attributes.newTab,
					//idValue:0,
					iconMaster:n.attributes.icono,
					title:n.text
				};
				var esBuscador=true;
				this.cargarTab(params,esBuscador);
			}
        }, this);
		
		this.cmbEmpresas.on('select',function(combo, record, index){			
			this.seleccionarEmpresa(record.data.id_empresa);
		},this);
		
		this.cmbSucursales.on('select',function(combo, record, index){			
			this.seleccionarSucursal(record.data.id_sucursal);
		},this);
		
		this.cmbAlmacenes.on('select',function(combo, record, index){			
			this.seleccionarAlmacen(record.data.id_almacen,record.data.nombre_almacen);
		},this);
		
		this.cmbEmpresas.addListener('beforequery',function(qe){
			qe.combo.expand();
			qe.combo.store.load();
			return false; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbSucursales.addListener('beforequery',function(qe){
			qe.combo.expand();
			qe.combo.store.load();
			return false;
		},this);
		
		this.cmbAlmacenes.addListener('beforequery',function(qe){
			qe.combo.expand();
			qe.combo.store.load();
			return false;
		},this);
		/*
		var tasksession = {
					run: this.VerificarSesion,
					interval: 5 * 60 * 1000,
					// interval: 10 * 1000,
					scope:this
				};
				Ext.TaskMgr.start(tasksession);	*/
		/*	
		this.cronTask = new Ext.util.DelayedTask(function(){
		//this.VerificarSesion();
		});			
		this.VerificarSesion();	
		*/
    },
	obtenerInformacionInicial:function(){
		Ext.Ajax.request({
        url: "app.php/sistema/getparametros",
		scope:this,
        success: function(response){            
            var resp=eval ('('+response.responseText+")");
            
			
			miErpWeb.parametros=resp.Parametros;
            miErpWeb.parametros.registros_pagina=parseInt(miErpWeb.parametros.registros_pagina);
            miErpWeb.User=resp.User;
            miErpWeb.UserConfig=resp.UserConfig;
            miErpWeb.Empresa=resp.Empresa;
            
            miErpWeb.Corporativo=resp.Corporativo;
            miErpWeb.Sucursal=resp.Sucursal;
			miErpWeb.Almacen=resp.Almacen;
						 
			 if ( undefined!=resp.prohibidos){
				 miErpWeb.prohibidos=resp.prohibidos;
			}else{
				miErpWeb.prohibidos=new Array();
			}
			
			miErpWeb.parametros.ciudad.nombre_ciudad=miErpWeb.formatearTexto(miErpWeb.parametros.ciudad.nombre_ciudad);
			miErpWeb.parametros.ciudad.nombre_estado=miErpWeb.formatearTexto(miErpWeb.parametros.ciudad.nombre_estado);
			miErpWeb.parametros.ciudad.nombre_pais=miErpWeb.formatearTexto(miErpWeb.parametros.ciudad.nombre_pais);
			
			this.actualizarHeader(resp);
		
        },
        failure: function(response){
			Ext.Msg.alert("Error en el servidor","No se recibieron los parámetros de configuración");            
        }
    });
	},
	actualizarHeader: function (data){
		
			this.lblNombreCorporativo.setValue(data.Corporativo.NomCor);
			this.lblNombreUsuario.setValue(data.UserConfig.nomUsu);
			this.lblUsuario.setValue(data.UserConfig.emaUsu);
			// this.pnlLogo.tpl('<img src="images/logos/lagranbelleza.jpg" height = "10px;" weight = "10px;"/>');
			var imagen = "";
			if(data.Empresa[0].logotipo_sucursal == 1)
				imagen = data.Sucursal[0].logotipo;
			else 
				imagen = data.Empresa[0].logotipo;
			//$("#foto").html("<img alt='imagen usuario'' src='" + this.winUser.getImageUrl() + "'/>");
			this.boxImagen.el.dom.src = String.format('images/logos/{0}', imagen);
			//data.Empresa.logotipo;
			var empresas=data.Empresa;
			this.cmbEmpresas.store.loadData({data:empresas});			
			this.cmbEmpresas.reset();
            var numEmps=this.cmbEmpresas.store.getCount();                        
           
			if (numEmps>0){ //<--Siempre deberia ser >0, de lo contrario no permite avanzar
				var firstEmp=this.cmbEmpresas.store.getAt(0);
				var idFirstEmp=firstEmp.data.id_empresa;
				this.cmbEmpresas.setValue(idFirstEmp);
				
			}
			
			var sucursales=data.Sucursal;
			this.cmbSucursales.store.loadData({data:data.Sucursal});			
			// this.cmbSucursales.reset();
            var numSucs=this.cmbSucursales.store.getCount();                        
			
			if (numSucs>0){ //<--Siempre deberia ser >0, de lo contrario no permite avanzar
				var firstSuc=this.cmbSucursales.store.getAt(0);
				var idFirstSuc=firstSuc.data.id_sucursal;
				this.cmbSucursales.setValue(idFirstSuc);
				
			}
			
			var almacenes=data.Almacen;
			this.cmbAlmacenes.store.loadData({data:data.Almacen});			
			// this.cmbSucursales.reset();
            var numAlms=this.cmbAlmacenes.store.getCount();                        
			
			if (numAlms>0){ //<--Siempre deberia ser >0, de lo contrario no permite avanzar
				var firstAlm=this.cmbAlmacenes.store.getAt(0);
				var idFirstAlm=firstAlm.data.id_almacen;
				this.cmbAlmacenes.setValue(idFirstAlm);
				
			}
              
	},
	cargarTab:function(params,esBuscador){
			// var tab =  this.tabContainer.getItem(nodo.text);
			//console.log(nodo);
			// if (nodo.leaf) {
				      // if (tab == null) {
                            // tab = this.tabContainer.add({
                                // xtype:  nodo.attributes.newTab, id: nodo.text, title: nodo.text, closable: true, iconMaster:nodo.attributes.iconMaster
                            // });
                        // }
                        // this.tabContainer.setActiveTab(tab);
            // }
			esBuscador=esBuscador||false;
			
			if (params.xtype==undefined){
				Ext.Msg.show({
				   title:'El Módulo está desabilitado',
				   msg: 'Consulte al Administrador del Sistema',
				   buttons: Ext.Msg.OK,
				   animEl: 'elId',
				   icon: Ext.MessageBox.INFO
				});  
				return;
			}else{		
				//alert("Revisar Xtype");
				var indexof=miErpWeb.prohibidos.indexOf(params.xtype);
				if (indexof!=-1){
					Ext.Msg.show({
					   title:'Información de acceso',
					   msg: 'No tiene privilegios para realizar esta acción.<br/>Consulte con el administrador del sistema.',
					   buttons: Ext.Msg.OK,				   				  
					   icon: Ext.MessageBox.INFO
					});
					return false;
				}			
			}
			
			if(params.xtype == 'formPuntoVenta'){
				 var id_almacen = miErpWeb.Almacen[0].id_almacen;
				 if(id_almacen == null){
					 Ext.Msg.show({
						   title:'Información',
						   msg: 'Debe seleccionar un almacen para accesar al punto de venta',
						   buttons: Ext.Msg.OK,				   				  
						   icon: Ext.MessageBox.INFO
						});
						return false;
				 }
			}
			
			if(params.xtype == 'gridMovimientosAlmacen'){
				 var id_almacen = miErpWeb.Almacen[0].id_almacen;
				 if(id_almacen == null){
					 Ext.Msg.show({
						   title:'Información',
						   msg: 'Debe seleccionar un almacen para accesar a los movimientos de almacen',
						   buttons: Ext.Msg.OK,				   				  
						   icon: Ext.MessageBox.INFO
						});
						return false;
				 }
			}
			
			
			
			
			 var tabItems = this.tabContainer.items;
			var existe = false;
			var tab;
			  var tabId;
			var i;
			for (i=0; i<tabItems.getCount(); i++){
				tab = tabItems.items[i];
				
				if (tab.tabIdValue==undefined){
					tabId=tab.idValue;
				}else{
					tabId=tab.tabIdValue;
				}
			
				if (tab.xtype == params.xtype && tabId == params.idValue){
					this.tabContainer.setActiveTab(tab);     //<-------SI EXISTE LO MUESTRO DANDOLE EL FOCO
					existe = true;
					break;
				}
			
			}
			
			
			
			 // if (!existe){	
					
				// var iconClass=params.iconMaster;			
				// iconClass+=(esBuscador)?'':'_add';			
				// var parametros=Ext.applyIf(params,{                
					// closable: true,
					// iconCls:Ext.ux.TDGi.iconMgr.getIcon(iconClass)
				// });		
				 // console.log(parametros);	
				// tab=this.tabContainer.add(parametros);            
			// }
			
			 if (!existe){
				  // console.log('existe');
				var accion='';
				if (params.bullet==undefined){
					accion=(params.idValue==0)? 'add':'edit';
				}else{
					accion=params.bullet;
				}
				
				var iconCls= Ext.ux.TDGi.iconMgr.getIcon(params.iconMaster);
				
				tab=this.tabContainer.add(Ext.applyIf(params,{
					title:'loading',
					iconCls:iconCls,
					closable: true
				}));
			}
			/*-------------------------------------------------------------*/        
			tab.show();		               
			return tab; 
			
			
	},
	seleccionarEmpresa:function(empId){
			// var me = this;
       
		    Ext.Ajax.request({
            url: 'app.php/sistema/seleccionarempresa',
            params:{IDEmp:empId},
			scope:this,
            success: function(response){
				var resp=eval ('('+response.responseText+")");
						
				miErpWeb.Empresa=resp.data.Empresa;
				
				var imagen = "";
				if(resp.data.Empresa[0].logotipo_sucursal == 0)
					var imagen = resp.data.Empresa[0].logotipo;
			
			
				this.boxImagen.el.dom.src = String.format('images/logos/{0}', imagen);
				
				this.cerrarTodos();
				this.cmbAlmacenes.reset();	
				this.cmbSucursales.reset(); 
					
			}           
        });
	
	},
	seleccionarSucursal:function(sucId){
		 Ext.Ajax.request({
            url: 'app.php/sistema/seleccionarsucursal',
            params:{IDSuc:sucId},
			scope:this,
            success: function(response){
				var resp=eval ('('+response.responseText+")");
						
				miErpWeb.Sucursal=resp.data.Sucursal;
				
				if(resp.data.Sucursal[0].logotipo_sucursal == 1){
					var imagen = resp.data.Sucursal[0].logotipo;		
					this.boxImagen.el.dom.src = String.format('images/logos/{0}', imagen);					
				}
					
				
				// miErpWeb.Almacen=resp.data.Almacen;
				
				// var id_alm = resp.data.Almacen[0].id_almacen;
				// var nom_alm = resp.data.Almacen[0].nombre_almacen;
				
				this.cerrarTodos()
				this.cmbAlmacenes.reset();		
				// var almacenes=resp.data.Almacen;
				// this.cmbAlmacenes.store.loadData({data:almacenes});			
				//this.cmbSucursales.reset();
				// var numAlms=this.cmbAlmacenes.store.getCount();                        
			/*
			if (numAlms>0){ //<--Siempre deberia ser >0, de lo contrario no permite avanzar
				var firstAlm=this.cmbAlmacenes.store.getAt(0);
				var idFirstAlm=firstAlm.data.id_almacen;
				this.cmbAlmacenes.setValue(idFirstAlm);
				
				//this.seleccionarAlmacen(id_alm,nom_alm);
				
			}else{
				this.cmbAlmacenes.reset();   
			}
				*/
            
				
			}           
        });
		
	},
	seleccionarAlmacen:function(almId,nomAlm){
		    Ext.Ajax.request({
            url: 'app.php/sistema/seleccionaralmacen',
            params:{IDAlm:almId,NomAlm:nomAlm},
			scope:this,
            success: function(response){
				var resp=eval ('('+response.responseText+")");
				
				miErpWeb.Almacen=resp.data.Almacen;  
			}           
        });
	},
	cerrarTodos: function () {
        var tamanio = this.tabContainer.items.length;
        for (var $i = tamanio - 1; $i > 0; $i--) {
           this.tabContainer.remove(this.tabContainer.items.items[$i]);
        }
        
        this.tabContainer.setActiveTab(0);
    }/*,
	VerificarSesion: function(){
		Ext.Ajax.request({ // actualizar los certificados
		url: 'app.php/sistema/verificasesion2',
		
		success: function(data){
			
			var res = Ext.decode(data.responseText);
				if(res){
					
				}else{
					Ext.TaskMgr.stopAll();
					SuccessFalse(Ext.apply(r,{
						CallBack:function(){
							Ext.getBody().mask(uerpc.Wait);
							document.location.reload();
						},
						Scope:this
					}));
				}
				
			
			
				
		
			
		}
	});
		
		//this.cronTask.delay(10000); 
}
*/
});
Ext.reg('mew.Main', mew.Main);