/*
 * File: winAuditoria.ui.js
 * Date: Tue Jul 23 2019 21:42:31 GMT-0600 (Mountain Daylight Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

winAuditoriaUi = Ext.extend(Ext.Window, {
    title: 'Auditoria',
    width: 490,
    height: 295,
    modal: true,
    border: false,
    draggable: false,
    resizable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                padding: 10,
                border: false,
                itemId: 'formAuditoria',
                width: 470,
                ref: 'formAuditoria',
                items: [
                    {
                        xtype: 'container',
                        layout: 'vbox',
                        height: 180,
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                layout: 'column',
                                width: 400,
                                height: 90,
                                items: [
                                    {
                                        xtype: 'container',
                                        width: 350,
                                        layout: 'column',
                                        items: [
                                            {
                                                xtype: 'container',
                                                height: 80,
                                                width: 80,
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        height: 80,
                                                        width: 80,
                                                        html: '<img border="0" src="images/iconos/foto_user.png" width="80" height="80">'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                layout: 'form',
                                                width: 270,
                                                style: 'padding-left:5px;',
                                                items: [
                                                    {
                                                        xtype: 'displayfield',
                                                        fieldLabel: 'Usuario Alta',
                                                        anchor: '100%',
                                                        style: 'font-style: italic;',
                                                        labelStyle: 'font-style: italic;font-weight: bold;',
                                                        itemId: 'dspUsuarioAlta',
                                                        ref: '../../../../../dspUsuarioAlta'
                                                    },
                                                    {
                                                        xtype: 'displayfield',
                                                        fieldLabel: 'Fecha Alta',
                                                        anchor: '100%',
                                                        style: 'font-style: italic;',
                                                        labelStyle: 'font-style: italic;font-weight: bold;',
                                                        itemId: 'dspFechaAlta',
                                                        ref: '../../../../../dspFechaAlta'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 90,
                                        width: 100
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                height: 100,
                                layout: 'column',
                                items: [
                                    {
                                        xtype: 'container',
                                        width: 100,
                                        height: 90
                                    },
                                    {
                                        xtype: 'container',
                                        width: 350,
                                        height: 90,
                                        layout: 'column',
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: 'form',
                                                width: 270,
                                                style: 'padding-right:5px;',
                                                items: [
                                                    {
                                                        xtype: 'displayfield',
                                                        fieldLabel: 'Usuario Modif',
                                                        anchor: '100%',
                                                        style: 'text-align:right;font-style: italic;',
                                                        labelStyle: 'text-align:right;font-style: italic;font-weight: bold;',
                                                        itemId: 'dspUsuarioModif',
                                                        ref: '../../../../../dspUsuarioModif'
                                                    },
                                                    {
                                                        xtype: 'displayfield',
                                                        fieldLabel: 'Fecha Modif',
                                                        anchor: '100%',
                                                        style: 'text-align:right;font-style: italic;',
                                                        labelStyle: 'text-align:right;font-style: italic;font-weight: bold;',
                                                        itemId: 'dspFechaModif',
                                                        ref: '../../../../../dspFechaModif'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                height: 80,
                                                width: 80,
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        height: 80,
                                                        width: 80,
                                                        html: '<img border="0" src="images/iconos/foto_user.png" width="80" height="80">'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: 'form',
                        items: [
                            {
                                xtype: 'displayfield',
                                fieldLabel: 'ID Registro',
                                anchor: '100%',
                                labelStyle: 'font-style: italic;font-weight: bold;',
                                style: 'font-style: italic;',
                                itemId: 'dspIdReg',
                                ref: '../../dspIdReg'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            },
            {
                xtype: 'container',
                layout: 'hbox',
                height: 33,
                items: [
                    {
                        xtype: 'container',
                        width: 370
                    },
                    {
                        xtype: 'button',
                        text: 'Aceptar',
                        width: 100,
                        itemId: 'btnAceptar',
                        ref: '../btnAceptar'
                    }
                ]
            }
        ];
        winAuditoriaUi.superclass.initComponent.call(this);
    }
});
