/*
 * File: winDescuentos.js
 * Date: Mon Apr 23 2018 22:58:52 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

winDescuentos = Ext.extend(winDescuentosUi, {
	importe:0.00,
	totalventa:0.00,
	inicializarEvents:function(){
		var me = this;
		
		this.btnCancelar.on('click', function(){
			this.close();
		}, this);
		
		this.btnAceptar.on('click', function(){
			this.importe = this.txtImporteDescuento.getValue();
			console.log(this.importe);
			console.log(this.totalventa);
			if(this.importe > this.totalventa){
				Ext.Msg.alert('Aviso', 'El descuento no puede ser mayor al total de la venta.');
				return;
			}else{				
				this.fireEvent("descuentoSeleccionado", this.importe);
				this.close();
			}
			
			
		}, this);
			
	},
    initComponent: function() {
        winDescuentos.superclass.initComponent.call(this);
		this.inicializarEvents();
    }
});
Ext.reg('winDescuentos', winDescuentos);