/*
 * File: formPrueba.ui.js
 * Date: Mon Mar 11 2019 20:05:46 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formPruebaUi = Ext.extend(Ext.Panel, {
    title: 'Pruebas',
    autoScroll: true,
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                padding: 10,
                border: false,
                itemId: 'frmMain',
                region: 'center',
                ref: 'frmMain',
                items: [
                    {
                        xtype: 'button',
                        text: 'MyButton',
                        itemId: 'btnFechas',
                        ref: '../btnFechas'
                    }
                ]
            }
        ];
        formPruebaUi.superclass.initComponent.call(this);
    }
});
