/*
 * File: formPrueba.js
 * Date: Mon Mar 11 2019 19:28:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formPrueba = Ext.extend(formPruebaUi, {
    initComponent: function() {
        formPrueba.superclass.initComponent.call(this);
    }
});
Ext.reg('formPrueba', formPrueba);