/*
 * File: BORRAR2fileuploadfield.ui.js
 * Date: Mon Apr 18 2016 13:07:20 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

BORRAR2fileuploadfieldUi = Ext.extend(Ext.form.TextField, {
    width: 200,
    initComponent: function() {
        BORRAR2fileuploadfieldUi.superclass.initComponent.call(this);
    }
});
