/*
 * File: gridListaPrecios.ui.js
 * Date: Mon Nov 13 2017 23:54:19 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridListaPreciosUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Listas de Precios',
    store: 'storeGridListaPrecios',
    width: 833,
    height: 362,
    stripeRows: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    disabled: true,
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    itemId: 'cmbStatus',
                    name: 'status',
                    width: 100,
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'descripcion',
                header: 'Descripcion',
                sortable: true,
                width: 300,
                id: 'colDescripcion'
            }            
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridListaPreciosUi.superclass.initComponent.call(this);
    }
});
