/*
 * File: gridInventarios.ui.js
 * Date: Tue Feb 06 2018 01:06:02 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridInventariosUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Inventarios',
    store: 'storeGridInventarios',
    width: 869,
    height: 330,
    stripeRows: true,
    autoExpandColumn: 'colConcepto',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    disabled: true,
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'displayfield',
                    value: 'Periodo:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'datefield',
                    ref: '../txtFechaini'
                },
                {
                    xtype: 'container',
                    width: 5
                },
                {
                    xtype: 'datefield',
                    ref: '../txtFechafin'
                },
                {
                    xtype: 'container',
                    width: 10
                },
                {
                    xtype: 'button',
                    text: 'Buscar',
                    icon: 'images/iconos/buscar.png',
                    ref: '../btnBuscar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    itemId: 'cmbStatus',
                    name: 'status',
                    width: 100,
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Serie - Folio',
                sortable: true,
                width: 100,
                dataIndex: 'serie_folio',
                id: 'colSerieFolio'
            },
            {
                xtype: 'gridcolumn',
                header: 'Fecha',
                sortable: true,
                width: 100,
                dataIndex: 'fecha_inventario'
            },
            {
                xtype: 'gridcolumn',
                header: 'Almacen',
                sortable: true,
                width: 200,
                dataIndex: 'nombre_almacen'
            },
            {
                xtype: 'gridcolumn',
                header: 'Concepto',
                sortable: true,
                width: 300,
                dataIndex: 'concepto_inventario',
                id: 'colConcepto'
            },
            {
                xtype: 'gridcolumn',
                sortable: true,
                resizable: false,
                width: 25,
                dataIndex: 'aplicado',
                editable: false,
                align: 'center',
                id: 'colAplicado'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridInventariosUi.superclass.initComponent.call(this);
    }
});
