/*
 * File: miErpWeb.storeGridInventarios.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeGridInventarios = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeGridInventarios.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridInventarios',
			idProperty: 'id_inventario',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_inventario'
                },
				{
                    name: 'aplicado'
                },
				{
                    name: 'serie_folio',
                    type: 'string'
                },
				{
                    name: 'concepto_inventario',
                    type: 'string'
                },
				{
                    name: 'fecha_inventario',
                    type: 'string'
                },
				{
                    name: 'nombre_almacen',
                    type: 'string'
                },
				{
                    name: 'status'
                }
			
			],
            url: 'app.php/inventarios/obtenerinventarios'
        }, cfg));
    }
});
Ext.reg('storeGridInventarios', miErpWeb.storeGridInventarios);