/*
 * File: miErpWeb.storeFormAbonosClientes.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormAbonosClientes = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormAbonosClientes.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormAbonosClientes',
			idProperty: 'id_cliente',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_cliente'
                },
				{
                    name: 'nombre_fiscal',
                    type: 'string'
                }			
			],
            url: 'app.php/abonos/obtenerclientes'
        }, cfg));
    }
});
Ext.reg('storeFormAbonosClientes', miErpWeb.storeFormAbonosClientes);