/*
 * File: miErpWeb.storeFormAbonosRemisiones.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormAbonosRemisiones = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormAbonosRemisiones.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormAbonosRemisiones',
			idProperty: 'id_remision',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_remision'
                },
				{
                    name: 'id_cxc'
                },
				{
                    name: 'descripcion',
                    type: 'string'
                },
				{
                    name: 'total'
                },
				{
                    name: 'abonos'
                },
				{
                    name: 'saldo'
                }			
			],
            url: 'app.php/abonos/obtenerremisiones'
        }, cfg));
    }
});
Ext.reg('storeFormAbonosRemisiones', miErpWeb.storeFormAbonosRemisiones);