/*
 * File: gridClientes.ui.js
 * Date: Wed Feb 01 2017 00:31:27 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridClientesUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Buscar Clientes',
    store: 'storeGridClientes',
    height: 250,
    autoExpandColumn: 'colRazonSocial',
    stripeRows: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    disabled: true,
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    width: 100,
                    forceSelection: true,
                    allowBlank: false,
                    name: 'status',
                    hiddenName: 'status',
                    itemId: 'cmbStatus',
                    style: '',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator',
                    style: ''
                },
                {
                    xtype: 'textfield',
                    emptyText: 'Introduzca el texto a buscar',
                    width: 250,
                    ref: '../txtFiltro'
                }
            ]
        };
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'nombre_fiscal',
                header: 'Razón Social / Nombre Comercial',
                sortable: true,
                width: 300,
                align: 'left',
                id: 'colRazonSocial'
            },
            {
                xtype: 'gridcolumn',
                header: 'RFC',
                sortable: true,
                width: 100,
                dataIndex: 'rfc_cliente',
                id: 'colRFC'
            },
            {
                xtype: 'gridcolumn',
                header: 'Tipo Cliente',
                sortable: true,
                width: 130,
                dataIndex: 'tipo_cliente',
                id: 'colTipoCliente'
            },
            {
                xtype: 'gridcolumn',
                header: 'Contacto',
                sortable: true,
                width: 200,
                dataIndex: 'nombre_contacto',
                id: 'colContacto'
            },
            {
                xtype: 'gridcolumn',
                header: 'Telefonos',
                sortable: true,
                width: 150,
                dataIndex: 'telefono_contacto',
                id: 'colTelefonos'
            },
            {
                xtype: 'gridcolumn',
                header: 'Categoria',
                sortable: true,
                width: 150,
                dataIndex: 'nombre_categoria',
                id: 'colCategoria'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridClientesUi.superclass.initComponent.call(this);
    }
});
