/*
 * File: gridProductos.ui.js
 * Date: Sun Feb 05 2017 13:11:12 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridProductosUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Buscar Productos',
    store: 'storeGridProductos',
    width: 852,
    height: 250,
    autoExpandColumn: 'colDescripcion',
    stripeRows: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    disabled: true,
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'label',
                    text: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    width: 100,
                    itemId: 'cmbStatus',
                    name: 'status',
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'codigo',
                header: 'Codigo',
                sortable: true,
                width: 80,
                id: 'colCodigo'
            },
            {
                xtype: 'gridcolumn',
                header: 'Descripcion',
                sortable: true,
                width: 320,
                dataIndex: 'descripcion',
                id: 'colDescripcion'
            },
            {
                xtype: 'gridcolumn',
                header: 'Linea',
                sortable: true,
                width: 200,
                dataIndex: 'nombre_linea',
                id: 'colLinea'
            },
            {
                xtype: 'gridcolumn',
                header: 'Unidad de Medida',
                sortable: true,
                width: 100,
                dataIndex: 'unidad_medida',
                id: 'colUnidadMedida'
            },
            {
                xtype: 'gridcolumn',
                header: 'Precio',
                sortable: true,
                width: 80,
                align: 'right',
                dataIndex: 'precio_venta',
                id: 'colPrecio'
            },
            {
                xtype: 'gridcolumn',
                sortable: true,
                width: 25,
                dataIndex: 'tipo_producto',
                id: 'colTipoProducto'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridProductosUi.superclass.initComponent.call(this);
    }
});
