/*
 * File: formUnidadesMedidas.ui.js
 * Date: Sat Feb 11 2017 18:58:50 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formUnidadesMedidasUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Unidade de Medida',
    width: 820,
    height: 580,
    padding: 10,
    autoScroll: true,
    labelWidth: 120,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    icon: 'images/iconos/unidades_medida_add.png',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Desactivar',
                    icon: 'images/iconos/unidades_medida_todos.png',
                    disabled: true,
                    ref: '../btnDesactivar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    icon: 'images/iconos/unidades_medida_delete.png',
                    disabled: true,
                    ref: '../btnEliminar'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Codigo',
                width: 100,
                labelStyle: 'font-weight:bold;',
                name: 'codigo_unidad',
                allowBlank: false,
                ref: 'txtCodigoUnidad'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Descripcion',
                width: 400,
                name: 'descripcion_unidad',
                bubbleEvents: [
                    'cambioDeNombre'
                ],
                labelStyle: 'font-weight:bold;',
                allowBlank: false,
                ref: 'txtDescripcionUnidad'
            },
            {
                xtype: 'textfield',
                anchor: '100%',
                name: 'id_unidadmedida',
                bubbleEvents: [
                    'cambioDeId'
                ],
                hidden: true,
                ref: 'txtIdUnidadMedida'
            },
            {
                xtype: 'textfield',
                anchor: '100%',
                hidden: true,
                name: 'status',
                bubbleEvents: [
                    'cambioDeStatus'
                ],
                value: 'A',
                ref: 'txtStatus'
            }
        ];
        formUnidadesMedidasUi.superclass.initComponent.call(this);
    }
});
