/*
 * File: formMovimientosAlmacenWinMovimientos.ui.js
 * Date: Sat Jan 06 2018 13:21:14 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formMovimientosAlmacenWinMovimientosUi = Ext.extend(Ext.Window, {
    title: 'Movimientos de Almacen',
    width: 589,
    height: 273,
    modal: true,
    border: false,
    draggable: false,
    resizable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                items: [
                    {
                        xtype: 'container',
                        height: 35,
                        layout: 'column',
                        style: 'margin-top:10px;margin-left:10px',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'form',
                                width: 220,
                                items: [
                                    {
                                        xtype: 'datefield',
                                        fieldLabel: 'Fecha Inicio',
                                        itemId: 'txtFechaInicio',
                                        ref: '../../../txtFechaInicio'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'form',
                                width: 220,
                                style: '',
                                items: [
                                    {
                                        xtype: 'datefield',
                                        fieldLabel: 'Fecha Fin',
                                        itemId: 'txtFechaFin',
                                        ref: '../../../txtFechaFin'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'button',
                                        text: 'Buscar',
                                        itemId: 'btnFiltro',
                                        icon: 'images/iconos/buscar.png',
                                        ref: '../../../btnFiltro'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'grid',
                        itemId: 'gridMovimientos',
                        height: 200,
                        border: false,
                        hideBorders: true,
                        ref: '../gridMovimientos',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                header: 'Serie Folio',
                                sortable: true,
                                width: 70,
                                dataIndex: 'serie_folio'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Fecha Movimiento',
                                sortable: true,
                                width: 100,
                                dataIndex: 'fecha_movimiento'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Nombre Sucursal',
                                sortable: true,
                                width: 160,
                                dataIndex: 'nombre_sucursal'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Almacen Origen',
                                sortable: true,
                                width: 130,
                                dataIndex: 'nombre_almacen_origen'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Total',
                                sortable: true,
                                width: 90,
                                dataIndex: 'total',
                                align: 'right',
                                id: 'colTotalMovimiento'
                            }
                        ],
                        view: new Ext.grid.GridView({

                        })
                    }
                ]
            }
        ];
        formMovimientosAlmacenWinMovimientosUi.superclass.initComponent.call(this);
    }
});
