/*
 * File: formMovimientosAlmacen.ui.js
 * Date: Mon Apr 23 2018 13:44:54 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formMovimientosAlmacenUi = Ext.extend(Ext.Panel, {
    title: 'Movimientos de Almacen',
    autoScroll: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    itemId: 'btnGuardar',
                    icon: 'images/iconos/movimientos_almacen_add.png',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'splitbutton',
                    text: 'Imprimir',
                    itemId: 'btnImprimir',
                    icon: 'images/iconos/pdf.png',
                    disabled: true,
                    height: 22,
                    ref: '../btnImprimir',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Ticket',
                                itemId: 'btnTicket',
                                icon: 'images/iconos/ticket.png',
                                ref: '../../../btnTicket'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'PDF',
                                itemId: 'btnPDF',
                                icon: 'images/iconos/pdf.png',
                                ref: '../../../btnPDF'
                            }
                        ]
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    itemId: 'btnEliminar',
                    icon: 'images/iconos/movimientos_almacen_delete.png',
                    disabled: true,
                    ref: '../btnEliminar'
                }
            ]
        };
        this.items = [
            {
                xtype: 'form',
                padding: 10,
                border: false,
                itemId: 'frmMain',
                ref: 'frmMain',
                items: [
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                width: 790,
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        height: 40,
                                        width: 780,
                                        items: [
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                width: 250,
                                                items: [
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Serie',
                                                        width: 120,
                                                        displayField: 'nombre_serie',
                                                        valueField: 'id_serie',
                                                        name: 'id_serie',
                                                        itemId: 'cmbSerie',
                                                        forceSelection: true,
                                                        editable: false,
                                                        triggerAction: 'all',
                                                        hiddenValue: 'id_serie',
                                                        ref: '../../../../../cmbSerie'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                labelWidth: 60,
                                                width: 200,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Folio',
                                                        width: 100,
                                                        itemId: 'txtFolio',
                                                        name: 'folio_movimiento',
                                                        style: 'text-align:right;',
                                                        readOnly: true,
                                                        submitValue: false,
                                                        ref: '../../../../../txtFolio'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                labelWidth: 50,
                                                width: 180,
                                                items: [
                                                    {
                                                        xtype: 'datefield',
                                                        fieldLabel: 'Fecha',
                                                        width: 100,
                                                        itemId: 'txtFecha',
                                                        name: 'fecha_movimiento',
                                                        submitValue: false,
                                                        ref: '../../../../../txtFecha'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                labelWidth: 45,
                                                width: 200,
                                                items: [
                                                    {
                                                        xtype: 'timefield',
                                                        fieldLabel: 'Hora',
                                                        width: 100,
                                                        itemId: 'txtHora',
                                                        name: 'hora_movimiento',
                                                        format: 'g:i:s A',
                                                        ref: '../../../../../txtHora'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        height: 40,
                                        width: 780,
                                        items: [
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                width: 280,
                                                items: [
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Tipo Movimiento',
                                                        width: 170,
                                                        valueField: 'id_tipomovimiento',
                                                        displayField: 'nombre_movimiento',
                                                        name: 'id_tipomovimiento',
                                                        itemId: 'cmbTipoMovimiento',
                                                        allowBlank: false,
                                                        forceSelection: true,
                                                        triggerAction: 'all',
                                                        editable: false,
                                                        ref: '../../../../../cmbTipoMovimiento'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                labelWidth: 60,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Concepto',
                                                        width: 435,
                                                        itemId: 'txtConceptoMovimiento',
                                                        name: 'concepto_movimiento',
                                                        submitValue: false,
                                                        allowBlank: false,
                                                        validateOnBlur: false,
                                                        ref: '../../../../../txtConceptoMovimiento'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 40,
                                        layout: 'form',
                                        itemId: 'pnlAgente',
                                        hidden: true,
                                        ref: '../../../pnlAgente',
                                        items: [
                                            {
                                                xtype: 'combo',
                                                fieldLabel: 'Vendedor',
                                                width: 300,
                                                itemId: 'cmbAgente',
                                                name: 'id_agente',
                                                valueField: 'id_agente',
                                                displayField: 'nombre_agente',
                                                editable: false,
                                                triggerAction: 'all',
                                                hiddenValue: 'id_agente',
                                                ref: '../../../../cmbAgente'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        width: 780,
                                        items: [
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                width: 400,
                                                items: [
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Almacen Origen',
                                                        width: 275,
                                                        itemId: 'cmbAlmacenOrigen',
                                                        name: 'id_almacen_origen',
                                                        valueField: 'id_almacen',
                                                        displayField: 'nombre_almacen',
                                                        editable: false,
                                                        triggerAction: 'all',
                                                        hiddenValue: 'id_tipomovimiento',
                                                        ref: '../../../../../cmbAlmacenOrigen'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                layout: 'form',
                                                items: [
                                                    {
                                                        xtype: 'combo',
                                                        width: 275,
                                                        itemId: 'cmbAlmacenDestino',
                                                        name: 'id_almacen_destino',
                                                        valueField: 'id_almacen',
                                                        displayField: 'nombre_almacen',
                                                        editable: false,
                                                        triggerAction: 'all',
                                                        fieldLabel: 'Almacen Destino',
                                                        hiddenValue: 'id_almacen_destino',
                                                        ref: '../../../../../cmbAlmacenDestino'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                width: 200,
                                layout: 'table',
                                flex: 1,
                                layoutConfig: {
                                    columns: 2
                                },
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Importe:',
                                        width: 90,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 0,
                                        width: 90,
                                        style: 'text-align:right;font-size:14px;font-weight:bold',
                                        itemId: 'lblImporte',
                                        ref: '../../../lblImporte'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Descuento:',
                                        width: 90,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 0,
                                        width: 90,
                                        style: 'text-align:right;font-size:14px;font-weight:bold',
                                        itemId: 'lblDescuento',
                                        ref: '../../../lblDescuento'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Subtotal:',
                                        width: 90,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 0,
                                        width: 90,
                                        style: 'text-align:right;font-size:14px;font-weight:bold',
                                        itemId: 'lblSubtotal',
                                        ref: '../../../lblSubtotal'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Impuestos:',
                                        width: 90,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 0,
                                        width: 90,
                                        style: 'text-align:right;font-size:14px;font-weight:bold',
                                        itemId: 'lblImpuestos',
                                        ref: '../../../lblImpuestos'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Total:',
                                        width: 90,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 0,
                                        width: 90,
                                        style: 'text-align:right;font-size:14px;font-weight:bold',
                                        itemId: 'lblTotal',
                                        ref: '../../../lblTotal'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: '',
                        bubbleEvents: [
                            'cambioDeId'
                        ],
                        hidden: true,
                        hideLabel: true,
                        submitValue: false,
                        itemId: 'id_movimiento',
                        ref: '../txtIdMovimientoAlmacen'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        name: 'status',
                        value: 'A',
                        hidden: true,
                        hideLabel: true,
                        submitValue: false,
                        ref: '../txtStatus'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        hideLabel: true,
                        hidden: true,
                        itemId: 'txtTotalImporte',
                        name: 'importe',
                        submitValue: false,
                        ref: '../txtTotalImporte'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        hidden: true,
                        hideLabel: true,
                        itemId: 'txtTotalDescuento',
                        name: 'descuento',
                        submitValue: false,
                        ref: '../txtTotalDescuento'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        hidden: true,
                        hideLabel: true,
                        itemId: 'txtTotalSubtotal',
                        name: 'subtotal',
                        submitValue: false,
                        ref: '../txtTotalSubtotal'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        hidden: true,
                        hideLabel: true,
                        itemId: 'txtTotalImpuestos',
                        name: 'impuestos',
                        submitValue: false,
                        ref: '../txtTotalImpuestos'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',
                        anchor: '100%',
                        hidden: true,
                        hideLabel: true,
                        itemId: 'txtTotalMovimiento',
                        name: 'total',
                        submitValue: false,
                        ref: '../txtTotalMovimiento'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Productos',
                collapsible: true,
                width: 990,
                style: 'padding-left:0;border-width:1px 0 0 0;',
                bodyStyle: 'padding-left:10px;',
                layout: 'auto',
                items: [
                    {
                        xtype: 'container',
                        height: 30,
                        layout: 'form',
                        itemId: 'pnlMovimientos',
                        hidden: true,
                        ref: '../pnlMovimientos',
                        items: [
                            {
                                xtype: 'combo',
                                fieldLabel: 'Movimientos',
                                triggerClass: 'x-form-search-trigger',
                                width: 100,
                                itemId: 'cmbMovimiento',
                                enableKeyEvents: true,
                                ref: '../../cmbMovimiento'
                            }
                        ]
                    },
                    {
                        xtype: 'form',
                        border: false,
                        itemId: 'frmDetalles',
                        height: 60,
                        ref: '../frmDetalles',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 300,
                                        items: [
                                            {
                                                xtype: 'trigger',
                                                fieldLabel: 'Producto',
                                                labelSeparator: ' ',
                                                width: 300,
                                                itemId: 'cmbProducto',
                                                triggerClass: 'x-form-search-trigger',
                                                enableKeyEvents: true,
                                                selectOnFocus: true,
                                                name: 'descripcion',
                                                ref: '../../../../cmbProducto'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 50,
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                fieldLabel: 'Unidad',
                                                labelSeparator: ' ',
                                                width: 50,
                                                itemId: 'txtUnidadMedida',
                                                name: 'unidad_medida',
                                                readOnly: true,
                                                ref: '../../../../txtUnidadMedida'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 70,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Cantidad',
                                                labelSeparator: ' ',
                                                width: 70,
                                                itemId: 'txtCantidad',
                                                style: 'text-align:right;',
                                                allowBlank: false,
                                                ref: '../../../../txtCantidad'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 90,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Unitario',
                                                labelSeparator: ' ',
                                                width: 90,
                                                itemId: 'txtCosto',
                                                style: 'text-align:right;',
                                                allowBlank: false,
                                                ref: '../../../../txtCosto'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 90,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Importe',
                                                width: 90,
                                                labelSeparator: ' ',
                                                itemId: 'txtImporte',
                                                style: 'text-align:right;',
                                                readOnly: true,
                                                ref: '../../../../txtImporte'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 85,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Descuento',
                                                width: 85,
                                                labelSeparator: ' ',
                                                itemId: 'txtDescuento',
                                                style: 'text-align:right;',
                                                allowBlank: false,
                                                ref: '../../../../txtDescuento'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 85,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Impuestos',
                                                width: 85,
                                                labelSeparator: ' ',
                                                itemId: 'txtImpuestos',
                                                style: 'text-align:right;',
                                                readOnly: true,
                                                ref: '../../../../txtImpuestos'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        layout: 'form',
                                        labelAlign: 'top',
                                        width: 90,
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                fieldLabel: 'Total',
                                                width: 90,
                                                labelSeparator: ' ',
                                                itemId: 'txtTotal',
                                                style: 'text-align:right;',
                                                readOnly: true,
                                                ref: '../../../../txtTotal'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        width: 8
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'form',
                                        width: 50,
                                        items: [
                                            {
                                                xtype: 'button',
                                                height: 24,
                                                width: 24,
                                                icon: 'images/iconos/ventas_add_big.png',
                                                scale: 'large',
                                                style: 'margin-left:8px;margin-top:5px;',
                                                itemId: 'btnAgregar',
                                                ref: '../../../../btnAgregar'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'grid',
                        height: 240,
                        itemId: 'gridDetalles',
                        width: 970,
                        autoExpandColumn: 'colDescripcion',
                        ref: '../gridDetalles',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                sortable: true,
                                width: 25,
                                id: 'colDelete'
                            },
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'descripcion',
                                header: 'Descripcion',
                                sortable: true,
                                width: 250,
                                groupable: false,
                                id: 'colDescripcion'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'U.M.',
                                sortable: true,
                                width: 50,
                                dataIndex: 'unidad_medida',
                                id: 'colUnidadMedida'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Cantidad',
                                sortable: true,
                                width: 100,
                                dataIndex: 'cantidad',
                                align: 'right',
                                id: 'colCantidad'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Costo',
                                sortable: true,
                                width: 100,
                                dataIndex: 'costo',
                                align: 'right',
                                id: 'colCosto'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Importe',
                                sortable: true,
                                width: 100,
                                dataIndex: 'importe',
                                align: 'right',
                                id: 'colImporte'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Descuento',
                                sortable: true,
                                width: 100,
                                dataIndex: 'descuento',
                                align: 'right',
                                id: 'colDescuento'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Impuestos',
                                sortable: true,
                                width: 100,
                                dataIndex: 'impuestos',
                                align: 'right',
                                id: 'colImpuestos'
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Total',
                                sortable: true,
                                width: 100,
                                dataIndex: 'total',
                                align: 'right',
                                id: 'colTotal'
                            }
                        ],
                        view: new Ext.grid.GridView({

                        })
                    }
                ]
            }
        ];
        formMovimientosAlmacenUi.superclass.initComponent.call(this);
    }
});
