/*
 * File: formMovimientosAlmacen.js
 * Date: Mon Apr 17 2017 23:22:08 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formMovimientosAlmacen = Ext.extend(formMovimientosAlmacenUi, {
	edicion:false,
	edicionDetalle:false,
	indexDetalle:0,
	id_producto:0,
	inicializarStores:function(){
		this.cmbSerie.store =  new miErpWeb.storeFormMovimientosAlmacenSeries();
		
		this.cmbTipoMovimiento.store =  new miErpWeb.storeFormMovimientosAlmacenTiposMovimientos();
		
		this.cmbAlmacenOrigen.store =  new miErpWeb.storeFormMovimientosAlmacenAlmacenes();
		this.cmbAlmacenDestino.store =  new miErpWeb.storeFormMovimientosAlmacenAlmacenes();
		this.cmbProducto.store =  new miErpWeb.storeFormMovimientosAlmacenProductos();
		
		this.gridDetalles.store = new miErpWeb.storeFormMovimientosAlmacenGrid();
		this.cmbAgente.store =  new miErpWeb.storeFormMovimientosAlmacenAgentes();
		
	},
	inicializarEvents:function(){
		
		this.frmMain.on('actioncomplete',function(form,action){
			 if (action.result.success){
				 this.cargarDatos(action.result.data);
				 
			 }else{				
				return false;
			}			
		}, this);	
		
		this.cmbAlmacenOrigen.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbAlmacenDestino.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbAgente.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbAlmacenOrigen.store.on('beforeload',function(){
			this.cmbAlmacenOrigen.store.baseParams.id_empresa=miErpWeb.Empresa[0].id_empresa;
			this.cmbAlmacenOrigen.store.baseParams.id_sucursal=miErpWeb.Sucursal[0].id_sucursal;
		},this);
		
		this.cmbAlmacenDestino.store.on('beforeload',function(){
			this.cmbAlmacenDestino.store.baseParams.id_empresa=miErpWeb.Empresa[0].id_empresa;
			this.cmbAlmacenDestino.store.baseParams.id_sucursal=miErpWeb.Sucursal[0].id_sucursal;
		},this);
		
		
		this.cmbProducto.updateAlways = true;
		
		this.cmbProducto.on("keydown", function(cmb, e){
				if(e.getKey()==13){
					this.id_producto = 0;
					this.aceptaProducto();
				}
			}, this);
		 this.txtConceptoMovimiento.setValue=function(value){
			value=miErpWeb.formatearTexto(value);
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	//this.cambioDeNombre(value);
			this.fireEvent('cambioDeNombre',value);
		}; 
		this.txtCantidad.on('blur',function(){
			var cantidad = this.txtCantidad.getValue();
			var costo = this.txtCosto.getValue();
			var descuento = this.txtDescuento.getValue();
			var impuestos = this.txtImpuestos.getValue();
						
			this.calcularConcepto(cantidad,costo,descuento,impuestos);
		}, this);	
		
		this.txtCosto.on('blur',function(){
			var cantidad = this.txtCantidad.getValue();
			var costo = this.txtCosto.getValue();
			var descuento = this.txtDescuento.getValue();
			var impuestos = this.txtImpuestos.getValue();
						
			this.calcularConcepto(cantidad,costo,descuento,impuestos);
		}, this);	
		
		this.txtDescuento.on('blur',function(){
			var cantidad = this.txtCantidad.getValue();
			var costo = this.txtCosto.getValue();
			var descuento = this.txtDescuento.getValue();
			var impuestos = this.txtImpuestos.getValue();
						
			this.calcularConcepto(cantidad,costo,descuento,impuestos);
		}, this);
		
		this.btnAgregar.on('click',function(){
			/*if(this.cmbProducto.getRawValue()==""){
				Ext.Msg.alert('Aviso', 'Capture el Producto.', function(){
					this.btnAgregar.enable();
					this.cmbProducto.focus(false, true);
				}, this);
				return;
			}
			
			if (!this.frmDetalles.getForm().isValid()) {	//<---Si hay errores informa al usuario
			  Ext.Msg.show({
				   title:'Error al agregar el Producto',
				   msg: 'Por favor revise los campos marcados',
				   buttons: Ext.Msg.OK,
				   fn: function(){
						this.cmbProducto.focus();
						this.cmbProducto.allowBlank=true;
				   },			   
				   scope:this,
				   icon: Ext.MessageBox.WARNING
				});			
				return false;
			}
			
			var cant = this.txtCantidad.getValue();
			var cost = this.txtCosto.getValue();
			var desc = this.txtDescuento.getValue();
			var impu = this.txtImpuestos.getValue();
						
			this.calcularConcepto(cant,cost,desc,impu);
			
			var id_producto = this.id_producto;
			var existe = false;
			var indexDetalle = 0;
			var cantidad = 0;
			var costo = this.txtCosto.getValue();
			var importe = 0;
			var descuento = 0;
			var subtotal = 0;
			var impuestos = 0;
			var total = 0;
			
			
			
			var detalles = this.gridDetalles.getStore().getRange();
			indexDetalle = detalles.length;
			
			for(var x = 0; x<detalles.length; x++){
				if(detalles[x].data.id_producto == id_producto && detalles[x].data.costo == costo ){
					existe = true;
					indexDetalle = x;
					cantidad = detalles[x].data.cantidad;
					importe = detalles[x].data.importe;
					descuento = detalles[x].data.descuento;
					subtotal = detalles[x].data.importe - detalles[x].data.descuento;
					impuestos = detalles[x].data.impuestos;
					total = detalles[x].data.total;					
				}	
			}
			
			if(existe == false){
				var record = new this.gridDetalles.store.recordType({
					id_producto: this.id_producto,
					descripcion: this.cmbProducto.getRawValue(), 
					unidad_medida: this.txtUnidadMedida.getValue(),
					cantidad: this.txtCantidad.getValue(),
					costo: this.txtCosto.getValue(),
					importe: this.txtImporte.getValue(),
					descuento: this.txtDescuento.getValue(),
					subtotal: this.txtImporte.getValue() - this.txtDescuento.getValue(),
					impuestos: this.txtImpuestos.getValue(),
					total: this.txtTotal.getValue()
				}, Ext.id());
				
				this.gridDetalles.getStore().insert(0,record);
			}else{
				var record = this.gridDetalles.getStore().getAt(indexDetalle);
				if(this.edicionDetalle){					
					var can = this.txtCantidad.getValue();
					var imp = this.txtImporte.getValue();
					var des = this.txtDescuento.getValue();
					var sub = (this.txtImporte.getValue() - this.txtDescuento.getValue());
					var imps = this.txtImpuestos.getValue();
					var tot = this.txtTotal.getValue();
				}else{				
					var can = cantidad + this.txtCantidad.getValue();
					var imp = importe + this.txtImporte.getValue();
					var des = descuento + this.txtDescuento.getValue();
					var sub = subtotal + (this.txtImporte.getValue() - this.txtDescuento.getValue());
					var imps = impuestos + this.txtImpuestos.getValue();
					var tot = total + this.txtTotal.getValue();
				}
				record.set("cantidad",can);
				record.set("importe",imp);
				record.set("descuento",des);
				record.set("subtotal",sub);
				record.set("impuestos",imps);
				record.set("total",tot);
											
				this.gridDetalles.getStore().commitChanges();				
			}
			this.calcularTotales();
			this.frmDetalles.getForm().reset();
			this.cmbProducto.focus(true, 0);
			this.id_producto = 0;
			this.edicionDetalle=false;
			this.indexDetalle = 0;	
			*/
			
			this.agregarProducto();
		
		}, this);
		
		this.gridDetalles.getColumnModel().getColumnById("colDelete").renderer = function(v, m, rec){
			value = "<img class='btnEliminarDetalle' src='images/iconos/grid_chico_borrar.png' style='cursor:pointer;' />";
			return value;
		}
		
		this.gridDetalles.on("cellclick", function(Grid, rowIndex, columnIndex, e){
			var imgEl = Ext.get(e.getTarget());

			if(imgEl.hasClass("btnEliminarDetalle")){
				var record = this.gridDetalles.getStore().getAt(rowIndex);

				Ext.MessageBox.show({
					scope: this,
					title: "Aviso",
					msg: "Est&aacute; seguro de eliminar este detalle?",
					width: 320,
					buttons: Ext.Msg.YESNO,
					fn: function(btn){
						if(btn == "yes"){
							this.gridDetalles.getStore().removeAt(rowIndex);
							this.gridDetalles.getSelectionModel().selectRow(0);
							// this.gridDetalles.getStore().reload();
							this.calcularTotales();
							this.cmbProducto.focus(false, true);
							
						}else{
							this.cmbProducto.focus(false, true);	
						}
						
					}
				});
				
							
				
			}
				
		}, this);
		
		this.gridDetalles.on("celldblclick", function(Grid, rowIndex, columnIndex, e){
				var record = this.gridDetalles.getStore().getAt(rowIndex);
				this.indexDetalle = rowIndex;
				this.id_producto = record.data.id_producto;
				this.txtUnidadMedida.setValue(record.data.unidad_medida);
				this.txtCantidad.setValue(Ext.util.Format.number(record.data.cantidad,'0.0000'));
				this.cmbProducto.setValue(record.data.id_producto);
				this.cmbProducto.setRawValue(record.data.descripcion);
				this.txtCosto.setValue(Ext.util.Format.number(record.data.costo,'0.00'));
				this.txtImporte.setValue(Ext.util.Format.number(record.data.importe,'0.00'));
				this.txtDescuento.setValue(Ext.util.Format.number(record.data.descuento,'0.00'));
				this.txtImpuestos.setValue(Ext.util.Format.number(record.data.impuestos,'0.00'));
				this.txtTotal.setValue(Ext.util.Format.number(record.data.total,'0.00'));
				this.edicionDetalle = true;
				this.cmbProducto.setDisabled(true);
				this.txtCantidad.focus(true, 0);
				
			
			}, this);
		
		this.txtCantidad.on('specialkey',function(txt,e){
			if (e.getCharCode()==e.ENTER){
				this.txtCosto.focus(true,0);
			}			
		},this);
		
		this.txtCosto.on('specialkey',function(txt,e){
			if (e.getCharCode()==e.ENTER){
				this.txtDescuento.focus(true,0);
			}			
		},this);
		
		this.txtDescuento.on('specialkey',function(txt,e){
			if (e.getCharCode()==e.ENTER){
				this.btnAgregar.focus(true,0);
			}			
		},this);
		
		this.txtCantidad.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.txtCosto.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.txtImporte.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.txtDescuento.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.txtImpuestos.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.txtTotal.setValue=function(value){
			if (value!=''){
				value=miErpWeb.formatearMoneda(value);
			}			
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
		};
		
		this.cmbSerie.on('select',function(combo, record, index){
			this.txtFolio.setValue(record.get('foliosig'));				
		}, this);
		
		this.cmbTipoMovimiento.on('select',function(combo, record, index){
			this.pnlMovimientos.setVisible(false);
			this.cmbAgente.clearValue();
			this.pnlAgente.setVisible(false);
			var tipo_mov = record.get('tipo_movimiento');
			
			switch(tipo_mov){
				case '1':	    	
					this.cmbAlmacenOrigen.setDisabled(true);
					this.cmbAlmacenOrigen.clearValue();
					this.cmbAlmacenDestino.setDisabled(false);
					this.cmbAlmacenDestino.store.on('load',this.seleccionarPrimerAlmacenDestino,this);	
					this.cmbAlmacenDestino.store.load();
					this.pnlMovimientos.setVisible(true);
				break;
				case '2':	    
					this.cmbAlmacenOrigen.setDisabled(false);
					this.cmbAlmacenDestino.setDisabled(true);
					this.cmbAlmacenDestino.clearValue();
					this.cmbAlmacenOrigen.store.on('load',this.seleccionarPrimerAlmacenOrigen,this);	
					this.cmbAlmacenOrigen.store.load();
				break;
				case '3':
					this.cmbAlmacenOrigen.setDisabled(false);
					this.cmbAlmacenOrigen.store.on('load',this.seleccionarPrimerAlmacenOrigen,this);	
					this.cmbAlmacenOrigen.store.load();
					
					this.cmbAlmacenDestino.setDisabled(false);
					this.cmbAlmacenDestino.store.on('load',this.seleccionarPrimerAlmacenDestino,this);	
					this.cmbAlmacenDestino.store.load();
				break;
				case '4':	    
					this.cmbAlmacenOrigen.setDisabled(false);
					this.cmbAlmacenDestino.setDisabled(true);					
					this.cmbAlmacenDestino.clearValue();
					this.cmbAlmacenOrigen.store.on('load',this.seleccionarPrimerAlmacenOrigen,this);	
					this.cmbAlmacenOrigen.store.load();
					this.pnlAgente.setVisible(true);
					this.cmbAgente.setDisabled(false);
					
				break;
				default:	
					return;
				break;
			}	

			this.doLayout();
		}, this);
		
		this.on('cambioDeId',function(params){	
			var id=params.id;
			if (id==0){
				this.btnGuardar.setIcon('images/iconos/'+this.iconMaster+'_add.png');
			}else if (id>0){
				this.btnEliminar.setDisabled(false);
				//this.btnDesactivar.setDisabled(false);
				this.btnGuardar.setIcon('images/iconos/'+this.iconMaster+'_edit.png');
			}			
		},this);
		var me = this;
		this.cmbProducto.onTriggerClick = function(){
				
				this.busquedaProducto = new formMovimientosAlmacenWinProductos();
				this.busquedaProducto.show();
				
				this.busquedaProducto.on("productoSeleccionado", function(Id){
					
					me.id_producto = Id;
					me.cmbProducto.setValue('');
					me.aceptaProducto();
				}, this);
				
		}
		/*	
		var VentanaSKUS = new VentanaSeries(ventanaConfig);

				VentanaSKUS.on("SKUsSeleccionados", function(seleccionados){
					var record = this.gridDetalles.getSelectionModel().getSelected();
					record.data.SKUs = seleccionados;
				}, this);

				VentanaSKUS.on("VentanaCerrada", function(){
					var record = this.gridDetalles.getSelectionModel().getSelected();
					if(record.data.SKUs=="[]" || record.data.SKUs=="" || record.data.SKUs==undefined)
						if(record.data.Edicion!=1)
							this.gridDetalles.getStore().remove(record);
				}, this);

				VentanaSKUS.show();
		
		*/
		
		
		this.btnGuardar.on('click', function(){
			this.guardar();
		}, this );
		
		this.btnEliminar.on('click',function(){	
			this.eliminar();
			
		},this);
	
		this.btnTicket.on('click', function(){
			this.imprimirticket();
		}, this);
		
		this.btnPDF.on('click', function(){
			this.imprimir();
		}, this);
	
		this.cmbMovimiento.onTriggerClick = function(){
				
				this.busquedaMovimiento = new formMovimientosAlmacenWinMovimientos();
				this.busquedaMovimiento.show();
				
				this.busquedaMovimiento.on("movimientoSeleccionado", function(Id,SerFol){
					
					//me.id_movimiento = Id;
					// me.cmbVenta.setValue(SerFol);
					me.obtenerProductosMovimiento(Id);
				}, this);
				
		}
	
	},
	inicializarRenders:function(){
		var colMod=this.gridDetalles.getColumnModel();
		
		var column=colMod.getColumnById("colCantidad");
		column.renderer=function(val){
			return Ext.util.Format.cantidadConSeparadorDeMiles(val);
		};	
		
		column=colMod.getColumnById("colCosto");
		column.renderer=this.renderMoneda;
		
		column=colMod.getColumnById("colImporte");
		column.renderer=this.renderMoneda;
		
		column=colMod.getColumnById("colDescuento");
		column.renderer=this.renderMoneda;
		
		column=colMod.getColumnById("colImpuestos");
		column.renderer=this.renderMoneda;
		
		column=colMod.getColumnById("colTotal");
		column.renderer=this.renderMoneda;
				
	},
	initComponent: function() {
		formMovimientosAlmacen.superclass.initComponent.call(this);
		
		this.txtStatus.setValue=function(value){        	
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeStatus',{status:value});
		};
		
		 this.txtIdMovimientoAlmacen.setValue=function(value){
			Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeId',{id:value});
			
        };
		
		this.inicializarStores();
		this.inicializarEvents();
		this.inicializarRenders();
	},
	aceptaProducto:function(){
		if(this.cmbProducto.getValue != "" || this.id_producto > 0 ){
			//this.id_producto = 0;
			Ext.Ajax.request({
				scope: this,
				url: 'app.php/movimientosalmacen/obtenerproducto',
				params: {
					ID: this.id_producto,
					Descripcion: this.cmbProducto.getValue()
				},
				success: function(data, options){
					var respuesta = Ext.decode(data.responseText);
					
					if(respuesta.success==true){
						this.id_producto = respuesta.data[0].id_producto;
						//this.cmbProducto.setValue(respuesta.data[0].id_producto);
						this.cmbProducto.setRawValue(respuesta.data[0].descripcion);
						this.txtCosto.setValue(miErpWeb.formatearMoneda(respuesta.data[0].precio_compra));
						this.txtUnidadMedida.setValue(respuesta.data[0].codigo_unidad);
						this.txtCantidad.setValue(miErpWeb.formatearCantidad(1));
						this.txtDescuento.setValue(miErpWeb.formatearMoneda(0));
						
						this.calcularConcepto(1,respuesta.data[0].precio_compra,0,0);
						
						this.txtCantidad.focus(true,100);
						// this.id_producto = 0;
						} else {
							Ext.Msg.alert('Aviso', 'El Producto no existe, verifique por favor.', function(){
							this.id_producto = 0;	
							this.cmbProducto.focus(true, 0);
						}, this);
						
					}					
				}
			});
		}
	},
	agregarProducto: function(){
		if(this.cmbProducto.getRawValue()==""){
				Ext.Msg.alert('Aviso', 'Capture el Producto.', function(){
					this.btnAgregar.enable();
					this.cmbProducto.focus(false, true);
				}, this);
				return;
			}
			
			if (!this.frmDetalles.getForm().isValid()) {	//<---Si hay errores informa al usuario
			  Ext.Msg.show({
				   title:'Error al agregar el Producto',
				   msg: 'Por favor revise los campos marcados',
				   buttons: Ext.Msg.OK,
				   fn: function(){
						this.cmbProducto.focus();
						this.cmbProducto.allowBlank=true;
				   },			   
				   scope:this,
				   icon: Ext.MessageBox.WARNING
				});			
				return false;
			}
			
			var cant = this.txtCantidad.getValue();
			var cost = this.txtCosto.getValue();
			var desc = this.txtDescuento.getValue();
			var impu = this.txtImpuestos.getValue();
						
			this.calcularConcepto(cant,cost,desc,impu);
			
			var id_producto = this.id_producto;
			var existe = false;
			var indexDetalle = 0;
			var cantidad = 0;
			var costo = this.txtCosto.getValue();
			var importe = 0;
			var descuento = 0;
			var subtotal = 0;
			var impuestos = 0;
			var total = 0;
			
			
			
			var detalles = this.gridDetalles.getStore().getRange();
			indexDetalle = detalles.length;
			
			for(var x = 0; x<detalles.length; x++){
				if(detalles[x].data.id_producto == id_producto && detalles[x].data.costo == costo ){
					existe = true;
					indexDetalle = x;
					cantidad = detalles[x].data.cantidad;
					importe = detalles[x].data.importe;
					descuento = detalles[x].data.descuento;
					subtotal = detalles[x].data.importe - detalles[x].data.descuento;
					impuestos = detalles[x].data.impuestos;
					total = detalles[x].data.total;					
				}	
			}
			
			if(existe == false){
				var record = new this.gridDetalles.store.recordType({
					id_producto: this.id_producto,
					descripcion: this.cmbProducto.getRawValue(), 
					unidad_medida: this.txtUnidadMedida.getValue(),
					cantidad: this.txtCantidad.getValue(),
					costo: this.txtCosto.getValue(),
					importe: this.txtImporte.getValue(),
					descuento: this.txtDescuento.getValue(),
					subtotal: this.txtImporte.getValue() - this.txtDescuento.getValue(),
					impuestos: this.txtImpuestos.getValue(),
					total: this.txtTotal.getValue()
				}, Ext.id());
				
				this.gridDetalles.getStore().insert(0,record);
			}else{
				var record = this.gridDetalles.getStore().getAt(indexDetalle);
				if(this.edicionDetalle){					
					var can = this.txtCantidad.getValue();
					var imp = this.txtImporte.getValue();
					var des = this.txtDescuento.getValue();
					var sub = (this.txtImporte.getValue() - this.txtDescuento.getValue());
					var imps = this.txtImpuestos.getValue();
					var tot = this.txtTotal.getValue();
				}else{		
					var can = cantidad + this.txtCantidad.getValue();
					var imp = importe + this.txtImporte.getValue();
					var des = descuento + this.txtDescuento.getValue();
					var sub = subtotal + (this.txtImporte.getValue() - this.txtDescuento.getValue());
					var imps = impuestos + this.txtImpuestos.getValue();
					var tot = total + this.txtTotal.getValue();
				}
				record.set("cantidad",can);
				record.set("importe",imp);
				record.set("descuento",des);
				record.set("subtotal",sub);
				record.set("impuestos",imps);
				record.set("total",tot);
											
				this.gridDetalles.getStore().commitChanges();				
			}
			this.calcularTotales();
			this.frmDetalles.getForm().reset();
			this.cmbProducto.setDisabled(false);
			this.cmbProducto.focus(true, 0);
			this.id_producto = 0;
			this.edicionDetalle=false;
			this.indexDetalle = 0;			
		
	},
	calcularConcepto:function(cantidad,costo,descuento,impuesto){
		var subtotal = 0.000000;
		var total = 0.000000;
		var totalimpuesto = 0.000000;
		var importe = 0.000000;
		var totaldescuento = 0.000000;
		
		importe = cantidad * costo;
		totaldescuento =  descuento;
		subtotal = importe - totaldescuento;
		totalimpuesto = subtotal * (impuesto/100);
		total = subtotal + totalimpuesto;		
		
		this.txtImporte.setValue(miErpWeb.formatearMoneda(importe));
		this.txtImpuestos.setValue(miErpWeb.formatearMoneda(totalimpuesto));
		this.txtTotal.setValue(miErpWeb.formatearMoneda(total));	
	},
	calcularTotales:function(){
			var i=0;
			var numrecs=this.gridDetalles.store.data.length;
			//var importe=0,descuento=0,subtotal=0,impuestos=0,total=0;
			var importe=0,descuento=0,subtotal=0,impuestos=0,total=0;	
			
			for (i=0; i<numrecs; i++){
				rec=this.gridDetalles.store.getAt(i);		
				
				importe+=	parseFloat( rec.data.importe );
				descuento+=	parseFloat( rec.data.descuento );
				subtotal+=parseFloat( rec.data.importe - rec.data.descuento );
				impuestos+=	parseFloat(rec.data.impuestos );
				total+=		parseFloat( rec.data.total );			
			}


			//importe = this.gridDetalles.getStore().sum('importe');
			//descuento = this.gridDetalles.getStore().sum('descuento');
			//impuestos = this.gridDetalles.getStore().sum('impuestos');
			//total = this.gridDetalles.getStore().sum('total');
			//subtotal = importe - descuento
			
			this.lblImporte.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(importe));
			this.lblDescuento.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(descuento));
			this.lblSubtotal.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(subtotal));
			this.lblImpuestos.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(impuestos));
			this.lblTotal.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(total));

			this.txtTotalImporte.setValue(importe);
			this.txtTotalDescuento.setValue(descuento);
			this.txtTotalSubtotal.setValue(subtotal);
			this.txtTotalImpuestos.setValue(impuestos);
			this.txtTotalMovimiento.setValue(total);
		
	},
	renderMoneda:function(val){
		if (val<0){
			return "-$" + Ext.util.Format.monedaConSeparadorDeMiles(val*-1);
		}else{
			return "$" + Ext.util.Format.monedaConSeparadorDeMiles(val);
		}
		
	},
	cargarDatos:function(data){
		if (data.Movimiento==undefined ){
			Ext.Msg.show({
				   title:'Error ',
				   msg: 'Error en los datos del movimiento',
				   buttons: Ext.Msg.OK,				   				   
				   icon: Ext.MessageBox.WARNING
				});
			// miErpWeb.tabContainer.remove(this);	
			
			return;
		}
		var movimiento=data.Movimiento;
		
		var form=this.frmMain.getForm();		
        // form.setValues(movimiento);
		this.txtIdMovimientoAlmacen.setValue(movimiento.id_movimiento);
        var fechaMov=movimiento.fecha_movimiento;
	
		var dt = Date.parseDate(fechaMov, "d/m/Y H:i:s");
	       
        this.txtFecha.setValue(dt);
        this.txtHora.setValue(dt.format('H:i:s A'));
		this.txtFolio.setValue(movimiento.folio_movimiento);
		this.txtConceptoMovimiento.setValue(movimiento.concepto_movimiento);
		
		var importe = movimiento.importe;
		var descuento = movimiento.descuento;
		var subtotal = movimiento.subtotal;
		var impuestos = movimiento.impuestos;
		var total = movimiento.total;
		
		this.lblImporte.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(importe));
		this.lblDescuento.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(descuento));
		this.lblSubtotal.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(subtotal));
		this.lblImpuestos.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(impuestos));
		this.lblTotal.setValue("$"+Ext.util.Format.monedaConSeparadorDeMiles(total));

		this.txtTotalImporte.setValue(importe);
		this.txtTotalDescuento.setValue(descuento);
		this.txtTotalSubtotal.setValue(subtotal);
		this.txtTotalImpuestos.setValue(impuestos);
		this.txtTotalMovimiento.setValue(total);
		
		if (movimiento.id_movimiento==0){
			this.cmbSerie.store.baseParams.id_empresa=movimiento.id_empresa;		
			this.cmbSerie.store.baseParams.id_sucursal=movimiento.id_sucursal;	
			this.cmbSerie.store.on('load',this.cargarPrimerFolio,this);	
			this.cmbSerie.store.load();
			
		}else{/*	SI LA FACTURA YA EXISTE EN EL SERVIDOR, SE ESTABLECE UN NUEVO TITULO Y EL ICONO DEL TAB			*/
			var series={
				id_serie:movimiento.id_serie,
				nombre_serie:movimiento.serie_movimiento
			};
			this.cmbSerie.store.loadData({data:series});
			this.cmbSerie.setValue(series.id_serie);
			this.cmbSerie.setDisabled(true);
			
			var tipos_movimientos={
				id_tipomovimiento:movimiento.id_tipomovimiento,
				nombre_movimiento:movimiento.nombre_movimiento,
				tipo_movimiento:movimiento.tipo_movimiento
			};
			this.cmbTipoMovimiento.store.loadData({data:tipos_movimientos});
			
			var storeTipoMovimiento=this.cmbTipoMovimiento.store;
			var index=storeTipoMovimiento.find('id_tipomovimiento',movimiento.id_tipomovimiento);
			var rec=storeTipoMovimiento.getAt(index);
			
			this.cmbTipoMovimiento.setValue(tipos_movimientos.id_tipomovimiento);
			this.cmbTipoMovimiento.fireEvent('select',this.cmbTipoMovimiento,rec);
			
			this.cmbTipoMovimiento.setDisabled(true);
			this.cmbAlmacenOrigen.setDisabled(true);
			this.cmbAlmacenDestino.setDisabled(true);
			this.cmbAgente.setDisabled(true);
			this.txtFecha.setDisabled(true);
			this.txtHora.setDisabled(true);
			this.txtFolio.setDisabled(true);
			
			this.btnEliminar.setDisabled(false);
			this.btnImprimir.setDisabled(false);
			
			this.setTitle(movimiento.id_movimiento+"-"+movimiento.concepto_movimiento);
						
		}
		
		
		
		// ALMACEN DE ORIGEN
			var almacen_origen={
				id_almacen:movimiento.id_almacen_origen,
				nombre_almacen:movimiento.nombre_almacen_origen
			};
			this.cmbAlmacenOrigen.store.loadData({data:almacen_origen});
			this.cmbAlmacenOrigen.setValue(almacen_origen.id_almacen);

			// ALMACEN DESTINO
			var almacen_destino={
				id_almacen:movimiento.id_almacen_destino,
				nombre_almacen:movimiento.nombre_almacen_destino
			};
			this.cmbAlmacenDestino.store.loadData({data:almacen_destino});
			this.cmbAlmacenDestino.setValue(almacen_destino.id_almacen);
			
			// AGENTE
			var agente={
				id_agente:movimiento.id_agente,
				nombre_agente:movimiento.nombre_agente
			};
			this.cmbAgente.store.loadData({data:agente});
			this.cmbAgente.setValue(agente.id_agente);


						
			// this.cmbTipoMovimiento.fireEvent('select', this.cmbTipoMovimiento);
			// this.cmbTipoMovimiento.el.focus(false);
		
		
		//Cargar detalles
		var detalles=data.Detalles;
        if(detalles!=undefined){			
            this.gridDetalles.store.loadData({
                data:detalles
            });
            this.calcularTotales();
        }	

		this.el.unmask();	
	},
	cargarPrimerFolio:function(){			
		this.cmbSerie.store.removeListener('load',this.cargarPrimerFolio,this);
		var primerRecord=this.cmbSerie.store.getAt(0);			
		this.cmbSerie.setValue(primerRecord.data.id_serie);

		this.txtFolio.setValue(primerRecord.data.foliosig);
		
	},
	seleccionarPrimerAlmacenDestino:function(){
		this.cmbAlmacenDestino.store.removeListener('load',this.seleccionarPrimerAlmacenDestino,this);
		var primerRecord=this.cmbAlmacenDestino.store.getAt(0);			
		this.cmbAlmacenDestino.setValue(primerRecord.data.id_almacen);
		
	},
	seleccionarPrimerAlmacenOrigen:function(){
		this.cmbAlmacenOrigen.store.removeListener('load',this.seleccionarPrimerAlmacenOrigen,this);
		var primerRecord=this.cmbAlmacenOrigen.store.getAt(0);			
		this.cmbAlmacenOrigen.setValue(primerRecord.data.id_almacen);
		
	},
	obtenerProductosMovimiento: function(Id){
		Ext.Ajax.request({
				scope: this,
				url: 'app.php/movimientosalmacen/obtenerproductosmovimiento',
				params: {
					idMov: Id					
				},
				success: function(data, options){
					var respuesta = Ext.decode(data.responseText);
					
					if(respuesta.success==true){
						// alert(respuesta.data.Venta.id_venta);
						this.cargarDatosMovimiento(respuesta.data);
						
						} else {
							Ext.Msg.alert('Aviso', 'El movimiento no existe, verifique por favor.', function(){
							// this.id_producto = 0;	
							// this.cmbProducto.focus(true, 0);
						}, this);
						
					}					
				}
			});
	},
	cargarDatosMovimiento:function(data){
		if (data.Movimiento==undefined ){
			Ext.Msg.show({
				   title:'Error ',
				   msg: 'Error en los datos del movimiento',
				   buttons: Ext.Msg.OK,				   				   
				   icon: Ext.MessageBox.WARNING
				});
			// miErpWeb.tabContainer.remove(this);	
			
			return;
		}
		var movimiento=data.Movimiento;
		
		//var form=this.frmMain.getForm();		
        // form.setValues(movimiento);
		
		//Cargar detalles
		/*var detalles=data.Detalles;
        if(detalles!=undefined){			
            this.gridDetalles.store.loadData({
                data:detalles
            });
            this.calcularTotales();
        }	*/
		
		//inicio
		var detallesMovimiento=data.Detalles;
        if(detallesMovimiento!=undefined){
			var id_producto_movimiento = 0;
			var descripcion_movimiento = '';
			var unidad_medida_movimiento = '';
			var existe = false;
			var cantidad_movimiento = 0;
			var costo_movimiento = 0;
			var importe_movimiento = 0;
			var descuento_movimiento = 0;
			var subtotal_movimiento = 0;
			var impuestos_movimiento = 0;
			var total_movimiento = 0;
				
			for(var y = 0; y<detallesMovimiento.length; y++){	
				id_producto_movimiento = detallesMovimiento[y].id_producto;
				descripcion_movimiento = detallesMovimiento[y].descripcion;
				unidad_medida_movimiento = detallesMovimiento[y].unidad_medida;
				cantidad_movimiento = detallesMovimiento[y].cantidad;
				costo_movimiento = detallesMovimiento[y].costo;
				importe_movimiento = detallesMovimiento[y].importe;
				descuento_movimiento = detallesMovimiento[y].descuento;
				subtotal_movimiento = detallesMovimiento[y].importe;
				impuestos_movimiento = detallesMovimiento[y].impuestos;
				total_movimiento = detallesMovimiento[y].total;	
				
				var indexDetalle = 0;
				var cantidad = 0;
				var costo = 0;
				var importe = 0;
				var descuento = 0;
				var subtotal = 0;
				var impuestos = 0;
				var total = 0;
				
				
				
				var detalles = this.gridDetalles.getStore().getRange();
				indexDetalle = detalles.length;
				
				for(var x = 0; x<detalles.length; x++){
					if(detalles[x].data.id_producto == id_producto_movimiento && detalles[x].data.costo == costo_movimiento ){
						existe = true;
						indexDetalle = x;
						cantidad = detalles[x].data.cantidad;
						importe = detalles[x].data.importe;
						descuento = detalles[x].data.descuento;
						subtotal = detalles[x].data.importe - detalles[x].data.descuento;
						impuestos = detalles[x].data.impuestos;
						total = detalles[x].data.total;					
					}	
				}
				
				if(existe == false){
					var record = new this.gridDetalles.store.recordType({
						id_producto: id_producto_movimiento,
						descripcion: descripcion_movimiento, 
						unidad_medida: unidad_medida_movimiento,
						cantidad: parseFloat(cantidad_movimiento),
						costo: parseFloat(costo_movimiento),
						importe: parseFloat(importe_movimiento),
						descuento: parseFloat(descuento_movimiento),
						subtotal: parseFloat(subtotal_movimiento),
						impuestos: parseFloat(impuestos_movimiento),
						total: parseFloat(total_movimiento)
					}, Ext.id());
					
					this.gridDetalles.getStore().insert(0,record);
				}else{
					var record = this.gridDetalles.getStore().getAt(indexDetalle);
					var can = parseFloat(cantidad) + parseFloat(cantidad_movimiento);
					var imp = parseFloat(importe) + parseFloat(importe_movimiento);
					var des = parseFloat(descuento) + parseFloat(descuento_movimiento);
					var sub = parseFloat(subtotal) + parseFloat(subtotal_movimiento);
					var imps = parseFloat(impuestos) + parseFloat(impuestos_movimiento);
					var tot = parseFloat(total) + parseFloat(total_movimiento);
					
					record.set("cantidad",can);
					record.set("importe",imp);
					record.set("descuento",des);
					record.set("subtotal",sub);
					record.set("impuestos",imps);
					record.set("total",tot);
												
					this.gridDetalles.getStore().commitChanges();				
				}
				
				
				id_producto_movimiento = 0;
				descripcion_movimiento = '';
				unidad_medida_movimiento = '';
				cantidad_movimiento = 0;
				importe_movimiento = 0;
				descuento_movimiento = 0;
				subtotal_movimiento = 0;
				impuestos_movimiento = 0;
				total_movimiento = 0;	
				
				id_producto = 0;
				existe = false;
				indexDetalle = 0;
				cantidad = 0;
				costo = 0;
				importe = 0;
				descuento = 0;
				subtotal = 0;
				impuestos = 0;
				total = 0;
			}
			
			this.calcularTotales();
		
		}
		
		this.el.unmask();	
	},
	guardar:function(){
		if (this.frmMain.getForm().isValid()){
			var conceptos=gridToJson(this.gridDetalles);
			var fecha = this.txtFecha.getValue();
			fecha=fecha.format('Y-m-d');   
			var params={};
			//params['Movimiento[id_empresa]'] = this.txtIdMovimientoAlmacen.getValue();
			params['Movimiento[id_empresa]'] = miErpWeb.Empresa[0].id_empresa;
			params['Movimiento[id_sucursal]'] = miErpWeb.Sucursal[0].id_sucursal;
			params['Movimiento[id_movimiento_almacen]'] = this.txtIdMovimientoAlmacen.getValue();
			params['Movimiento[id_serie]'] = this.cmbSerie.getValue();
			params['Movimiento[nombre_serie]'] = this.cmbSerie.getRawValue();
			params['Movimiento[folio_movimiento]'] = this.txtFolio.getValue();
			params['Movimiento[fecha]'] = fecha; 
			params['Movimiento[hora]'] =this.txtHora.getValue();
			params['Movimiento[concepto_movimiento]'] = this.txtConceptoMovimiento.getValue();
			params['Movimiento[id_tipomovimiento]'] = this.cmbTipoMovimiento.getValue();
			params['Movimiento[id_almacen_origen]'] = this.cmbAlmacenOrigen.getValue();
			params['Movimiento[id_almacen_destino]'] = this.cmbAlmacenDestino.getValue();
			params['Movimiento[id_agente]'] = this.cmbAgente.getValue();
			params['Movimiento[importe]'] = this.txtTotalImporte.getValue();
			params['Movimiento[descuento]'] = this.txtTotalDescuento.getValue();
			params['Movimiento[subtotal]'] = this.txtTotalSubtotal.getValue();
			params['Movimiento[impuestos]'] = this.txtTotalImpuestos.getValue();
			params['Movimiento[total]'] = this.txtTotalMovimiento.getValue();
			params['Movimiento[status]'] = this.txtStatus.getValue();

			params['Conceptos']=conceptos;
			
			var id_tipomov = this.cmbTipoMovimiento.getValue();
		    var store=this.cmbTipoMovimiento.getStore();
		    var index=store.find('id_tipomovimiento', id_tipomov);
		    	 
		    var rec=store.getAt(index);
			
			params['Movimiento[tipo_movimiento]'] = rec.data.tipo_movimiento;
			
			
			this.el.mask('Guardando...');
			this.frmMain.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/movimientosalmacen/save',
				success:function(){
					this.el.unmask();
				},
				failure:function(form, action){
					this.el.unmask();
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					
					}
				});
				
			
		}else{
			return;
			
		}	
		
		
	},
	getParamsImprimir:function(){
		return {
			IDMov:this.txtIdMovimientoAlmacen.getValue()
		};
	},
	imprimirticket:function(){
		var params=this.getParamsImprimir();			
		Ext.Ajax.request({
		params: params,
		   url: 'app.php/movimientosalmacen/generarreportemovimiento',
		   success: function(response, opts){
				//Solicita el PDF
				var obj = Ext.decode(response.responseText);
				if (!obj.success){	//Prosegir solo en caso de exito
					return;
				}
				var identificador=obj.data.identificador;
				window.open("app.php/movimientosalmacen/getpdfmovimiento?identificador="+identificador,'rep_mov',"height=600,width=800");							
			},
		   failure: function(){
				alert("El servidor ha respondido con un mensaje de error");
			}						   
		   
		});
	},
	imprimir:function(){
		var params=this.getParamsImprimir();			
		Ext.Ajax.request({
		params: params,
		   url: 'app.php/movimientosalmacen/generarreportemovimientocarta',
		   success: function(response, opts){
				//Solicita el PDF
				var obj = Ext.decode(response.responseText);
				if (!obj.success){	//Prosegir solo en caso de exito
					return;
				}
				var identificador=obj.data.identificador;
				window.open("app.php/movimientosalmacen/getpdfmovimientocarta?identificador="+identificador,'rep_mov',"height=600,width=800");							
			},
		   failure: function(){
				alert("El servidor ha respondido con un mensaje de error");
			}						   
		   
		});
	},
	eliminar:function(btn){
		switch(btn){	//ESTE SWITCH ES USADO PARA ANALIZAR LO QUE TRATA DE HACER EL USUARIO, LA PRIERA VEZ DEBE ENTRAR A default:
    	case 'no':
    		return;
    	break;
    	case 'yes':
    		this.eliminar('borrar');
    		return;
    		break;
    	case 'borrar':
    		break;		//SALE DEL SWITCH Y SIGUE EJECUTANDOSE LA FUNCI�N
    	case undefined:	//AQUI ENTRA LA PRIMERA VEZ
    	case false:    		
    	default:
    		var me=this;    		
    		Ext.Msg.show({
 			   title:'Confirme por favor',
 			   msg: "¿Desea borrar el movimiento?",
 			   buttons: Ext.Msg.YESNO,
 			   fn: function(btn){	    				
    				me.eliminar(btn);
    			},
 			   scope:this,
 			   icon: Ext.MessageBox.QUESTION
 			});
    		return;
		} 
		this.el.mask(mew.mensajeDeEspera);
		Ext.Ajax.request({
			params: { id_movimiento: this.txtIdMovimientoAlmacen.getValue() },
			scope:this,
		   	url: 'app.php/movimientosalmacen/eliminar',
		   	success: function(response,options){	
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==false){
					this.el.unmask();
					return;
				}
				
				this.fireEvent('eliminado',options.params.id_movimiento);
				MainContainer.tabContainer.remove(this);
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},
	listeners:{
    	activate:function(){
			
    		if (this.activado==true){
    			return;
    		}
    		this.activado=true;
    	
			if (this.idValue!=undefined && this.idValue!=0){
    			this.txtIdMovimientoAlmacen.setValue(this.idValue);
				//this.el.mask(mfw.mensajeDeEspera);    			
    		}
                          
			this.frmMain.load({
				params:{idMov:this.idValue,
						id_empresa:miErpWeb.Empresa[0].id_empresa,
						id_sucursal:miErpWeb.Sucursal[0].id_sucursal,
						id_almacen:miErpWeb.Almacen[0].id_almacen				
				},
				url:'app.php/movimientosalmacen/obtenermovimiento'
			});
			
			return false;
					
    	},
    	cambioDeNombre:function(nombre){
    		this.setTitle(Ext.util.Format.ellipsis(this.idValue+'-'+nombre,25,true));
		},
    	cambioDeId:function(params){
    		var id=params.id;
    		this.idValue=id;
    		if (id==0){
				this.setIconClass(Ext.ux.TDGi.iconMgr.getIcon(this.iconMaster+"_add"));
			}else if (id>0){
				this.setIconClass(Ext.ux.TDGi.iconMgr.getIcon(this.iconMaster+"_edit"));				
			}
					
    	}
    }
});
Ext.reg('formMovimientosAlmacen', formMovimientosAlmacen);