/*
 * File: mfw.almacenes.storeFormMovimientosAlmacenTiposMovimientos.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormMovimientosAlmacenTiposMovimientos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormMovimientosAlmacenTiposMovimientos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormMovimientosAlmacenTiposMovimientos',
            idProperty: 'id_tipomovimiento',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_tipomovimiento'
                },
				{
                    name: 'nombre_movimiento',
                    type: 'string'
                },
				{
                    name: 'tipo_movimiento',
					type: 'string'
                },				
				
			],
            url: 'app.php/movimientosalmacen/obtenertiposmovimientos'
        }, cfg));
    }
});
Ext.reg('storeFormMovimientosAlmacenTiposMovimientos', miErpWeb.storeFormMovimientosAlmacenTiposMovimientos);
