/*
 * File: mfw.almacenes.storeFormReporteVentasAgentes.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormReporteVentasAgentes = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormReporteVentasAgentes.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormReporteVentasAgentes',
			autoDestroy: true,
            idProperty: 'id_agente',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_agente'
                },
				{
                    name: 'nombre_agente',
                    type: 'string'
                }				
			],
            url: 'app.php/ventas/obteneragentes'
        }, cfg));
    }
});
Ext.reg('storeFormReporteVentasAgentes', miErpWeb.storeFormReporteVentasAgentes);
