/*
 * File: formChecador.js
 * Date: Sun Jun 11 2017 14:02:01 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formChecador = Ext.extend(formChecadorUi, {
	id_empleado:0,
	initComponent: function() {
        formChecador.superclass.initComponent.call(this);
		
		
		this.inicializarEvents();
		
    },
	inicializarEvents: function(){
		var me = this;
		
		this.frmMain.on('actioncomplete',function(form,action){
			 if (action.result.success){				
				this.lblHora.setValue(action.result.data.fecha_hora);
				this.lblMensaje.setValue(action.result.data.mensaje);	
				this.cmbEmpleado.focus(false, true);				  
			 }else{				
				return false;
			}			
		}, this);
		
		this.on('afterrender', function(){		
			this.cmbEmpleado.reset();
			this.lblHora.setValue('');
			this.lblMensaje.setValue('');	
			this.cmbEmpleado.focus(false, true);
		}, this);	
		
		this.cmbEmpleado.on("keydown", function(cmb, e){
				if(e.getKey()==13){
					this.id_empleado = 0;
					this.guardar();
				}
			}, this);
	},
	guardar: function(){
		if (this.frmMain.getForm().isValid()){
			   
			var params={};
			
			params['Checada[codigo_empleado]'] = this.cmbEmpleado.getValue();			
			
			this.el.mask('Guardando...');
			this.frmMain.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/checadas/guardar',
				success:function(data, options){
					this.el.unmask();
					this.cmbEmpleado.reset();
					this.cmbEmpleado.focus(false, true);
					
					
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.cmbEmpleado.reset();
					this.lblHora.setValue('');
					this.lblMensaje.setValue('');
					this.el.unmask(); 
					this.cmbEmpleado.focus(false, true);
					}
				});
				
			
		}else{
			return;
			
		}	
	}	
				
	
});
Ext.reg('formChecador', formChecador);