/*
 * File: xds_index.js
 * Date: Sat Jul 13 2019 01:30:40 GMT-0600 (Mountain Daylight Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new formChecador({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
