/*
 * File: gridTurnos.ui.js
 * Date: Mon Nov 13 2017 23:54:31 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridTurnosUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Turnos',
    store: 'storeGridTurnos',
    width: 833,
    height: 362,
    stripeRows: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    disabled: true,
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'displayfield',
                    value: 'Periodo:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'datefield',
                    ref: '../txtFechaInicio'
                },
                {
                    xtype: 'container',
                    width: 5
                },
                {
                    xtype: 'datefield',
                    ref: '../txtFechaFin'
                },
                {
                    xtype: 'container',
                    width: 10
                },
                {
                    xtype: 'button',
                    text: 'Buscar',
                    icon: 'images/iconos/buscar.png',
                    ref: '../btnBuscar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    itemId: 'cmbStatus',
                    name: 'status',
                    width: 100,
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'concepto',
                header: 'Concepto',
                sortable: true,
                width: 300,
                id: 'colConcepto'
            },
            {
                xtype: 'gridcolumn',
                header: 'Fecha Inicio',
                sortable: true,
                width: 100,
                dataIndex: 'fechainicio'
            },
            {
                xtype: 'gridcolumn',
                header: 'Fecha Fin',
                sortable: true,
                width: 100,
                dataIndex: 'fechafin'
            },
            {
                xtype: 'gridcolumn',
                header: 'Total',
                sortable: true,
                width: 100,
                dataIndex: 'total',
                align: 'right',
                id: 'colTotal'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridTurnosUi.superclass.initComponent.call(this);
    }
});
