/*
 * File: miErpWeb.storeGridTurnos.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeGridTurnos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeGridTurnos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridTurnos',
			idProperty: 'id_turno',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_turno'
                },
				{
                    name: 'concepto',
                    type: 'string'
                },
				{
                    name: 'fechainicio',
                    type: 'string'
                },
				{
                    name: 'fechafin',
                    type: 'string'
                },
				{
                    name: 'status'
                },
				{
                    name: 'total',
                    type: 'string'
                }
			
			],
            url: 'app.php/turnos/obtenerturnos'
        }, cfg));
    }
});
Ext.reg('storeGridTurnos', miErpWeb.storeGridTurnos);