/*
 * File: miErpWeb.loginStoreEmpresas.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.loginStoreEmpresas = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.loginStoreEmpresas.superclass.constructor.call(this, Ext.apply({
            storeId: 'loginStoreEmpresas',
            root: 'data',
            fields:["id_empresa","nombre_fiscal"],
            url: 'app.php/login/getnegocios'
        }, cfg));
    }
});
Ext.reg('loginStoreEmpresas', miErpWeb.loginStoreEmpresas);new miErpWeb.loginStoreEmpresas();