/*
 * File: xds_index.js
 * Date: Sun Mar 13 2016 18:17:12 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new main({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
