/*
 * File: formClientesCategorias.ui.js
 * Date: Sat Feb 11 2017 18:58:50 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formClientesCategoriasUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Categorias de Clientes',
    width: 820,
    height: 580,
    padding: 10,
    autoScroll: true,
    labelWidth: 120,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    icon: 'images/iconos/conceptos_add.png',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Desactivar',
                    icon: 'images/iconos/conceptos_red.png',
                    disabled: true,
                    ref: '../btnDesactivar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    icon: 'images/iconos/conceptos_delete.png',
                    disabled: true,
                    ref: '../btnEliminar'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre Categoria',
                width: 400,
                name: 'nombre_categoria',
                bubbleEvents: [
                    'cambioDeNombre'
                ],
                labelStyle: 'font-weight:bold;',
                allowBlank: false,
                ref: 'txtNombreCategoria'
            },
            {
                xtype: 'textfield',
                anchor: '100%',
                name: 'id_cliente_categoria',
                bubbleEvents: [
                    'cambioDeId'
                ],
                hidden: true,
                ref: 'txtIdClienteCategoria'
            },
            {
                xtype: 'textfield',
                anchor: '100%',
                hidden: true,
                name: 'status',
                bubbleEvents: [
                    'cambioDeStatus'
                ],
                value: 'A',
                ref: 'txtStatus'
            }
        ];
        formClientesCategoriasUi.superclass.initComponent.call(this);
    }
});
