/*
 * File: miErpWeb.storeClientesCiudades.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeClientesCiudades = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeClientesCiudades.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeClientesCiudades',
			 autoDestroy: true,
			 // autoLoad:true,
			idProperty: 'id_ciu',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[{
						name: 'id_ciu',
						type: 'int'
					},{
						name: 'nom_ciu',
						type: 'string'
					},{
						name: 'id_est',
						type: 'int'
					},{
						name: 'nom_est',
						type: 'string'
					},{
						name: 'id_pai',
						type: 'int'
					},{
						name: 'nom_pai',
						type: 'string'
					},{
						name: 'img_pai',
						type: 'string',
						formatear: false
					}
			],
            url: 'app.php/ciudades/obtenerciudades'
        }, cfg));
    }
});
Ext.reg('storeClientesCiudades', miErpWeb.storeClientesCiudades);//new miErpWeb.storeClientesCiudades();