/*
 * File: formReporteCatalogoClientes.js
 * Date: Sun Jun 18 2017 23:47:22 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formReporteCatalogoClientes = Ext.extend(formReporteCatalogoClientesUi, {
	inicializarStores: function() {		
		this.cmbCategorias.store = new miErpWeb.storeFormReporteCatalogoClientesCategorias();
		this.cmbCategorias.store.load();
	},
	inicializarEvents: function() {
		var me = this;
		
		this.cmbCategorias.addListener('beforequery', function(qe) {
			delete qe.combo.lastQuery;
		}, this);		
		
		this.btnPDF.on('click', function(){
			this.imprimir();
		}, this);
		
		this.btnExcel.on('click', function(){
			this.imprimirExcel();
		}, this);
		
		this.cmbCategorias.onTriggerClick = function(a, e) {
			if (e) {
				if (e.getAttribute('class').indexOf('x-form-clear-trigger') > -1) {
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					}
					if (!Ext.isEmpty(me.cmbCategorias.getValue())) {
						this.reset();
					}
				} else {
					if (this.readOnly || this.disabled) {
						return;
					}
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					} else {
						this.onFocus({});
						if (this.triggerAction == 'all') {
							this.doQuery(this.allQuery, true);
						} else {
							this.doQuery(this.getRawValue());
						}
						this.el.focus();
					}
				}
			}
		};
		
	},	
	initComponent: function() {
		formReporteCatalogoClientes.superclass.initComponent.call(this);
		this.inicializarStores();
		this.inicializarEvents();		
	},
	getParamsImprimir: function() {
		return {			
			IDCat: Ext.num(this.cmbCategorias.getValue(), 0),			
			nombre_categoria: (this.cmbCategorias.getRawValue() == "") ? 'TODAS' : this.cmbCategorias.getRawValue()
		};
	},
	imprimir: function() {
		if (!this.getForm().isValid()) {
			return false;
		}
		
		var params = this.getParamsImprimir();
		Ext.Ajax.request({
			params: params,
			url: 'app.php/clientes/generarreporteclientescategorias',
			success: function(response, opts){
				//Solicita el PDF
				var obj = Ext.decode(response.responseText);
				if (!obj.success){	//Prosegir solo en caso de exito
					return;
				}
				var identificador=obj.data.identificador;
				window.open("app.php/clientes/getpdfclientescategorias?identificador="+identificador,'rep_mov',"height=600,width=800");							
			},
			failure: function(){
				alert("El servidor ha respondido con un mensaje de error");
			}						   
			
		});
	},
	imprimirExcel:function(){
		if (!this.getForm().isValid()) {	//<---Si hay errores informa al usuario
			 return false;
		}
		var params=this.getParamsImprimir();				
		
		location.href = "app.php/clientes/generarreporteclientescategoriasexcel?IDCat="+params.IDCat;
		
		//window.open("app.php/ventas/getpdfventasproductos?identificador="+identificador,'rep_mov',"height=600,width=800");
	}

});
Ext.reg('formReporteCatalogoClientes', formReporteCatalogoClientes);