/*
 * File: miErpWeb.storeFormCortesDenominacionesRetencion.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designneer version 1.1.2.
 * http://www.sencha.com/products/desigr/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormCortesDenominacionesRetencion = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormCortesDenominacionesRetencion.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormCortesDenominacionesRetencion',
			idProperty: 'id_denominacion',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_denominacion'
                },
				{
                    name: 'denominacion',
                    type: 'string'
                }				
			],
            url: 'app.php/cortes/obtenerdenominaciones'
        }, cfg));
    }
});
Ext.reg('storeFormCortesDenominacionesRetencion', miErpWeb.storeFormCortesDenominacionesRetencion);