/*
 * File: gridSeries.ui.js
 * Date: Wed Feb 01 2017 00:32:23 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridSeriesUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Buscar Series',
    store: 'storeGridSeries',
    width: 820,
    height: 250,
    stripeRows: true,
    initComponent: function() {
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'nombre_serie',
                header: 'Serie',
                sortable: true,
                width: 100,
                id: 'colNombreSerie'
            },
            {
                xtype: 'numbercolumn',
                header: 'Folio Inicio',
                sortable: true,
                width: 100,
                align: 'right',
                dataIndex: 'folioinicio',
                id: 'colFolioInicio'
            },
            {
                xtype: 'numbercolumn',
                header: 'Folio Fin',
                sortable: true,
                width: 100,
                align: 'right',
                dataIndex: 'foliofin',
                id: 'colFolioFin'
            },
            {
                xtype: 'numbercolumn',
                header: 'Folio Sig.',
                sortable: true,
                width: 100,
                align: 'right',
                dataIndex: 'foliosig',
                id: 'colFolioSig'
            },
            {
                xtype: 'gridcolumn',
                header: 'Tipo',
                sortable: true,
                width: 150,
                dataIndex: 'tipo_serie',
                id: 'colTipoSerie'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'label',
                    text: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    width: 100,
                    itemId: 'cmbStatus',
                    name: 'status',
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.bbar = {
            xtype: 'paging',
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridSeriesUi.superclass.initComponent.call(this);
    }
});
