/*
 * File: miErpWeb.storeGridSeries.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeGridSeries = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeGridSeries.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridSeries',
			idProperty: 'id_serie',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_serie'
                },
				{
                    name: 'nombre_serie',
                    type: 'string'
                },
				{
                    name: 'folioinicio',
                    type: 'int'
                },
				{
                    name: 'foliofin',
                    type: 'int'
                },
				{
                    name: 'foliosig',
                    type: 'int'
                },
				{
                    name: 'tipo_serie',
                    type: 'string'
                },
				{
                    name: 'status'
                }
			
			],
            url: 'app.php/series/obtenerseries'
        }, cfg));
    }
});
Ext.reg('storeGridSeries', miErpWeb.storeGridSeries);