/*
 * File: formReporteCarteraClientes.js
 * Date: Sun Jun 18 2017 23:47:22 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formReporteCarteraClientes = Ext.extend(formReporteCarteraClientesUi, {
	inicializarStores: function(){
		this.cmbAgente.store =  new miErpWeb.storeFormReporteCarteraClientesAgentes();
		
		this.cmbCliente.store =  new miErpWeb.storeFormReporteCarteraClientes();
	},
	inicializarEvents: function(){
		var me = this;
		this.cmbAgente.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbCliente.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);		
		
		this.btnEjecutar.on('click', function(){
			this.imprimir();
		}, this);
		
		this.cmbCliente.onTriggerClick = function(a, e){
			if(e){
				if(e.getAttribute('class').indexOf('x-form-clear-trigger') > -1){
					if(this.isExpanded()){
						this.collapse();
						this.el.focus();
					}
					if(!Ext.isEmpty(me.cmbCliente.getValue())){
						this.reset();
						
						// this.deshabilitarBtns(true);
						// this.cntActivo.setVisible(false);
						// this.spExcel.setVisible(false);
						//this.reloadGrid(null, 0);
					}
				}else{
					if(this.readOnly || this.disabled){
						return;
					}
					if(this.isExpanded()){
						this.collapse();
						this.el.focus();
					}else {
						this.onFocus({});
						if(this.triggerAction == 'all') {
							this.doQuery(this.allQuery, true);
						} else {
							this.doQuery(this.getRawValue());
						}
						this.el.focus();
					}
				} 
			}
		};
		
	},
    initComponent: function() {
        formReporteCarteraClientes.superclass.initComponent.call(this);
		this.inicializarStores();
		this.inicializarEvents();
    },
	getParamsImprimir:function(){
		return {
			IDAge:Ext.num(this.cmbAgente.getValue(),0),
			IDCli:Ext.num(this.cmbCliente.getValue(),0),
			IDEmp:Ext.num(miErpWeb.Empresa[0].id_empresa,0),
			IDSuc:Ext.num(miErpWeb.Sucursal[0].id_sucursal,0)
		};
	},
	imprimir:function(){
		if (!this.getForm().isValid()) {	//<---Si hay errores informa al usuario
			 return false;
		}
		var params=this.getParamsImprimir();			
		Ext.Ajax.request({
		params: params,
		   url: 'app.php/clientes/generarreportecartera',
		   success: function(response, opts){
				//Solicita el PDF
				var obj = Ext.decode(response.responseText);
				if (!obj.success){	//Prosegir solo en caso de exito
					return;
				}
				var identificador=obj.data.identificador;
				window.open("app.php/clientes/getpdfreportecartera?identificador="+identificador,'rep_mov',"height=600,width=800");							
			},
		   failure: function(){
				alert("El servidor ha respondido con un mensaje de error");
			}						   
		   
		});
	}
});
Ext.reg('formReporteCarteraClientes', formReporteCarteraClientes);