/*
 * File: miErpWeb.storeFormRemisionesGrid.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormRemisionesGrid = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormRemisionesGrid.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormRemisionesGrid',
			idProperty: 'id_remision_detalle',
			root: 'data',
			autoDestroy: true,
			fields:[
				{
                    name: 'id_remision_detalle'
                },
				{
                    name: 'id_producto'
                },
				{
                    name: 'descripcion',
                    type: 'string'
                },
				{
                    name: 'unidad_medida',
                    type: 'string'
                },
				{
                    name: 'cantidad',
                    type: 'float'                   
                },
				{
                    name: 'costo',
                    type: 'float'
                },
				{
                    name: 'importe',
                    type: 'float'
                },
				{
                    name: 'descuento',
                    type: 'float'
                },
				{
                    name: 'subtotal',
                    type: 'float'
                },
				{
                    name: 'impuestos',
                    type: 'float'
                },
				{
                    name: 'total',
                    type: 'float'
                }
			
			]           
        }, cfg));
    }
});
Ext.reg('storeFormRemisionesGrid', miErpWeb.storeFormRemisionesGrid);