/*
 * File: xds_index.js
 * Date: Tue Dec 25 2018 23:46:10 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new formRemisiones({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
