/*
 * File: gridChequeras.ui.js
 * Date: Fri Jan 18 2019 23:09:41 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridChequerasUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Chequeras',
    store: 'storeGridChequeras',
    width: 820,
    height: 250,
    stripeRows: true,
    initComponent: function() {
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'descripcion',
                header: 'Descripcion',
                sortable: true,
                width: 500,
                id: 'colNombreChequera'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'label',
                    text: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    width: 100,
                    itemId: 'cmbStatus',
                    name: 'status',
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.bbar = {
            xtype: 'paging',
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridChequerasUi.superclass.initComponent.call(this);
    }
});
