/*
 * File: miErpWeb.storeGridCotizaciones.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeGridCotizaciones = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeGridCotizaciones.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridCotizaciones',
			idProperty: 'id_cotizacion',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_cotizacion'
                },
				{
                    name: 'serie_folio',
                    type: 'string'
                },
				{
                    name: 'concepto',
                    type: 'string'
                },
				{
                    name: 'fecha',
                    type: 'string'
                },
				{
                    name: 'nombre_cliente',
                    type: 'string'
                },
				{
                    name: 'total',
                    type: 'string'
                },
				{
                    name: 'status'
                }
			
			],
            url: 'app.php/cotizaciones/obtenercotizaciones'
        }, cfg));
    }
});
Ext.reg('storeGridCotizaciones', miErpWeb.storeGridCotizaciones);