/*
 * File: miErpWeb.storeFormMaximosMinimosGrid.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormMaximosMinimosGrid = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormMaximosMinimosGrid.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormMaximosMinimosGrid',
			idProperty: 'id_producto',
			root: 'data',
			autoDestroy: true,
			fields:[
				{
                    name: 'id_almacen'
                },
				{
                    name: 'id_producto'
                },
				{
                    name: 'codigo',
                    type: 'string'
                },
				{
                    name: 'descripcion',
                    type: 'string'
                },
				{
                    name: 'stock_min',
                    type: 'float'                   
                },
				{
                    name: 'stock_max',
                    type: 'float'
                },
				{
                    name: 'modificado',
                    type: 'tinyint'
                }
			
			]           
        }, cfg));
    }
});
Ext.reg('storeFormMaximosMinimosGrid', miErpWeb.storeFormMaximosMinimosGrid);