/*
 * File: mfw.almacenes.storeFormMovimientosAlmacenTiposMovimientos.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormMovimientosCajaTipos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormMovimientosCajaTipos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormMovimientosCajaTipos',
            root: 'data',
			fields:[
				{
                   name: 'id',
					 type: 'string'
                },
				{
                    name: 'nombre',
                    type: 'string'
                }				
				
			]           
        }, cfg));
    }
});
Ext.reg('storeFormMovimientosCajaTipos', miErpWeb.storeFormMovimientosCajaTipos);
