/*
 * File: mfw.almacenes.storeFormReporteSaldosLineasSucursales.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('miErpWeb');
miErpWeb.storeFormReporteSaldosLineasSucursales = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        miErpWeb.storeFormReporteSaldosLineasSucursales.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeFormReporteSaldosLineasSucursales',
			autoDestroy: true,
            idProperty: 'id_linea',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_sucursal'
                },
				{
                    name: 'nombre_sucursal',
                    type: 'string'
                },
				{
                    name: 'id_empresa'
                },
				{
                    name: 'nombre_empresa',
                    type: 'string'
                }	
			],
            url: 'app.php/ventas/obtenersucursales'
        }, cfg));
    }
});
Ext.reg('storeFormReporteSaldosLineasSucursales', miErpWeb.storeFormReporteSaldosLineasSucursales);
