/*
 * File: formHorarios.ui.js
 * Date: Fri Jul 12 2019 23:50:15 GMT-0600 (Mountain Daylight Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formHorariosUi = Ext.extend(Ext.Panel, {
    title: 'Horario',
    autoScroll: true,
    labelWidth: 120,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    icon: 'images/iconos/calendar_add.png',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Desactivar',
                    icon: 'images/iconos/calendar_todos.png',
                    disabled: true,
                    ref: '../btnDesactivar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    icon: 'images/iconos/calendar_delete.png',
                    disabled: true,
                    ref: '../btnEliminar'
                }
            ]
        };
        this.items = [
            {
                xtype: 'form',
                border: false,
                padding: 10,
                itemId: 'frmMain',
                ref: 'frmMain',
                items: [
                    {
                        xtype: 'timefield',
                        itemId: 'txtHoraInicio',
                        editable: false,
                        name: 'hora_inicio',
                        increment: 10,
                        width: 100,
                        allowBlank: false,
                        bubbleEvents: [
                            'cambioDeNombre'
                        ],
                        format: 'g:i:s A',
                        fieldLabel: 'Hora Inicio',
                        labelStyle: 'font-weight:bold',
                        ref: '../txtHoraInicio'
                    },
                    {
                        xtype: 'timefield',
                        name: 'hora_fin',
                        width: 100,
                        editable: false,
                        allowBlank: false,
                        increment: 10,
                        itemId: 'txtHoraFin',
                        format: 'g:i:s A',
                        fieldLabel: 'Hora Fin',
                        labelStyle: 'font-weight:bold',
                        ref: '../txtHoraFin'
                    },
                    {
                        xtype: 'textfield',
                        name: 'id_horario',
                        bubbleEvents: [
                            'cambioDeId'
                        ],
                        hidden: true,
                        ref: '../txtIdHorario'
                    },
                    {
                        xtype: 'textfield',
                        hidden: true,
                        name: 'status',
                        bubbleEvents: [
                            'cambioDeStatus'
                        ],
                        value: 'A',
                        ref: '../txtStatus'
                    }
                ]
            }
        ];
        formHorariosUi.superclass.initComponent.call(this);
    }
});
