/*
 * File: gridEmpleados.ui.js
 * Date: Thu Jul 11 2019 13:02:25 GMT-0600 (Mountain Daylight Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridEmpleadosUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Buscar Empleados',
    store: 'storeGridEmpleados',
    width: 805,
    height: 250,
    stripeRows: true,
    autoExpandColumn: 'colNombreEmpleado',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    ref: '../btnAgregar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    disabled: true,
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'label',
                    text: 'Status:',
                    style: 'margin-right:5px;'
                },
                {
                    xtype: 'combo',
                    width: 100,
                    itemId: 'cmbStatus',
                    name: 'status',
                    triggerAction: 'all',
                    mode: 'local',
                    displayField: 'nombre',
                    valueField: 'id',
                    forceSelection: true,
                    allowBlank: false,
                    hiddenName: 'status',
                    editable: false,
                    ref: '../cmbStatus'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    width: 250,
                    emptyText: 'Introduzca el texto a buscar',
                    ref: '../txtFiltro'
                }
            ]
        };
        this.view = new Ext.grid.GridView({

        });
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'codigo_empleado',
                header: 'Codigo Empleado',
                sortable: true,
                width: 150,
                editable: false,
                id: 'colCodigoEmpleado'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'nombre_empleado',
                header: 'Nombre Empleado',
                sortable: true,
                width: 400,
                editable: false,
                id: 'colNombreEmpleado'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'celular',
                header: 'Celular',
                sortable: true,
                width: 150,
                editable: false,
                id: 'colCelular'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayMsg: 'Mostrando {0} - {1} de {2}',
            emptyMsg: 'No hay registros para mostrar'
        };
        gridEmpleadosUi.superclass.initComponent.call(this);
    }
});
