/*
 * File: formReporteFlujoEfectivo.js
 * Date: Sun Jun 18 2017 23:47:22 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('miErpWeb');
Ext.ns('mew');
formReporteFlujoEfectivo = Ext.extend(formReporteFlujoEfectivoUi, {
	inicializarStores: function() {
		this.cmbEmpresa.store = new miErpWeb.storeFormReporteFlujoEfectivoEmpresas();
		this.cmbSucursal.store = new miErpWeb.storeFormReporteFlujoEfectivoSucursales();
		this.cmbEmpresa.store.load();
		this.cmbSucursal.store.load();
	},
	inicializarEvents: function() {
		var me = this;
		var dt = new Date();
		this.txtFechaInicio.setValue(dt);
		this.txtFechaFin.setValue(dt);
		this.cmbEmpresa.addListener('beforequery', function(qe) {
			delete qe.combo.lastQuery;
		}, this);
		this.cmbSucursal.addListener('beforequery', function(qe) {
			delete qe.combo.lastQuery;
		}, this);
		this.cmbSucursal.getStore().on('beforeload', function() {
			this.cmbSucursal.store.baseParams.id_empresa = Ext.num(this.cmbEmpresa.getValue(), 0);
		}, this);
		this.cmbEmpresa.on('select', function(combo, record, index) {
			this.cmbSucursal.reset();
		}, this);
		this.btnEjecutar.on('click', function() {
			this.imprimir();
		}, this);
		this.cmbEmpresa.onTriggerClick = function(a, e) {
			if (e) {
				if (e.getAttribute('class').indexOf('x-form-clear-trigger') > -1) {
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					}
					if (!Ext.isEmpty(me.cmbEmpresa.getValue())) {
						this.reset();
						me.cmbSucursal.reset();
					}
				} else {
					if (this.readOnly || this.disabled) {
						return;
					}
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					} else {
						this.onFocus({});
						if (this.triggerAction == 'all') {
							this.doQuery(this.allQuery, true);
						} else {
							this.doQuery(this.getRawValue());
						}
						this.el.focus();
					}
				}
			}
		};
		this.cmbSucursal.onTriggerClick = function(a, e) {
			if (e) {
				if (e.getAttribute('class').indexOf('x-form-clear-trigger') > -1) {
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					}
					if (!Ext.isEmpty(me.cmbSucursal.getValue())) {
						this.reset();
					}
				} else {
					if (this.readOnly || this.disabled) {
						return;
					}
					if (this.isExpanded()) {
						this.collapse();
						this.el.focus();
					} else {
						this.onFocus({});
						if (this.triggerAction == 'all') {
							this.doQuery(this.allQuery, true);
						} else {
							this.doQuery(this.getRawValue());
						}
						this.el.focus();
					}
				}
			}
		};
		this.cmbEmpresa.store.on('load', function() {
			this.cmbEmpresa.setValue(Ext.num(miErpWeb.Empresa[0].id_empresa, 0));
		}, this);
	},
	inicializarTpls: function() {
		this.cmbSucursal.tpl = new Ext.XTemplate('<tpl for=".">' + '<div class="x-combo-list-item">' + '<div><b>{nombre_sucursal}</b></div>' + '<div><i>{nombre_empresa}</i></div>' + '</div>' + '</tpl>');
	},
	initComponent: function() {
		formReporteFlujoEfectivo.superclass.initComponent.call(this);
		this.inicializarStores();
		this.inicializarEvents();
		this.inicializarTpls();
	},
	getParamsImprimir: function() {
		return {
			IDEmp: Ext.num(this.cmbEmpresa.getValue(), 0),
			IDSuc: Ext.num(this.cmbSucursal.getValue(), 0),
			FechaIni: this.txtFechaInicio.getValue().dateFormat('Y-m-d'),
			FechaFin: this.txtFechaFin.getValue().dateFormat('Y-m-d'),
			PerdidasGanancias: this.chkPerdidasGanancias.checked ? 1 : 0,
			nombre_empresa: (this.cmbEmpresa.getRawValue() == "") ? 'TODAS' : this.cmbEmpresa.getRawValue(),
			nombre_sucursal: (this.cmbSucursal.getRawValue() == "") ? 'TODAS' : this.cmbSucursal.getRawValue()
		};
	},
	imprimir: function() {
		if (!this.getForm().isValid()) {
			return false;
		}
		if (this.chkPerdidasGanancias.checked && (this.cmbSucursal.getRawValue() == "" || this.cmbSucursal.getValue() == 0)) {
			Ext.Msg.show({
				title: 'Error ',
				msg: 'Debe seleccionar una sucursal',
				buttons: Ext.Msg.OK,
				icon: Ext.MessageBox.WARNING
			});
			return;
		}
		var params = this.getParamsImprimir();
		location.href = "app.php/ventas/generarreporteflujoefectivo?IDEmp=" + params.IDEmp + "&IDSuc=" + params.IDSuc + "&FechaIni=" + params.FechaIni + "&FechaFin=" + params.FechaFin + "&nombre_empresa=" + params.nombre_empresa + "&nombre_sucursal=" + params.nombre_sucursal + "&perdidas_ganancias=" + params.PerdidasGanancias;
	}
});
Ext.reg('formReporteFlujoEfectivo', formReporteFlujoEfectivo);