/*
 * File: winCancelaciones.js
 * Date: Thu Mar 11 2021 20:07:29 GMT-0700 (Mountain Standard Time (Mexico))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

winCancelaciones = Ext.extend(winCancelacionesUi, {
    id_movimiento: 0,
	tipo_movimiento: 0,
	inicializaEventos: function(){
		var me = this;
		
		this.btCancelar.on('click', function(){
			this.close();
		});
		
		this.btnAceptar.on('click', function(){
				
				//Ext.Msg.alert('Aviso', 'El descuento no puede ser mayor al total de la venta.');
				//return;
				
				//this.fireEvent("descuentoSeleccionado", this.importe);
				//this.close();
			Ext.Ajax.request({
				scope: this,
				url: 'app.php/sistema/cancelarmovimiento',
				params: {
					ID: this.id_movimiento,
					TipoMov: this.id_movimiento,
					Usuario: this.txtUsuario.getValue(),
					Password: this.txtPass.getValue()
				},
				success: function(data, options){
					var respuesta = Ext.decode(data.responseText);
					
					if(respuesta.success==true){
						Ext.Msg.alert('Aviso', 'Movimiento cancelado.');
						this.fireEvent("movimientocancelado", this.importe);
						this.close();
						
					} else {
							Ext.Msg.alert('Aviso', 'El usuario no puede cancelar el movimiento.');						
					}					
				}
			});
			
			
		}, this);
	},
	initComponent: function() {		
        winCancelaciones.superclass.initComponent.call(this);
		this.inicializaEventos();
    }
});
Ext.reg('winCancelaciones', winCancelaciones);